import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'app_language';

export const SUPPORTED_LANGUAGES = [
    { code: 'en', label: 'English', nativeName: 'English', flag: '🇬🇧' },
    { code: 'am', label: 'አማርኛ (Amharic)', nativeName: 'አማርኛ', flag: '🇪🇹' },
];

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState(() => {
        try {
            const saved = window.localStorage.getItem(STORAGE_KEY);
            if (saved === 'en' || saved === 'am') return saved;
        } catch {
        }
        return 'am';
    });

    useEffect(() => {
        try {
            window.localStorage.setItem(STORAGE_KEY, language);
        } catch {
        }
        document.documentElement.lang = language;
    }, [language]);

    const t = useMemo(
        () => (key, params) => {
            const dict = language === 'am' ? translationsAm : translationsEn;
            let text = dict[key] ?? translationsEn[key] ?? key;
            if (params) {
                Object.entries(params).forEach(([pKey, pValue]) => {
                    text = text.split(`{{${pKey}}}`).join(String(pValue));
                });
            }
            return text;
        },
        [language]
    );

    const value = useMemo(() => ({ language, setLanguage, t, isAmharic: language === 'am' }), [language, t]);

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
}

const translationsEn = {
    // Navigation
    'nav.home': 'Home',
    'nav.songs': 'Songs',
    'nav.performances': 'Worship',
    'nav.choirs': 'Choirs',
    'nav.about': 'About',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.dashboard': 'Dashboard',
    'nav.openMenu': 'Open menu',
    'nav.closeMenu': 'Close menu',
    'nav.memberArea': 'Member Area',

    // Brand
    'brand.choirPrimary': 'Yeka',
    'brand.choirSuffix': 'Choir',
    'brand.choirName': 'Yeka M.K.C Choir',

    // Footer
    'footer.tagline': 'A digital home for Yeka Meserete Kristos music and worship.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.history': 'History',
    'footer.emailUs': 'Email Us',
    'footer.website': 'Website',
    'footer.telegram': 'Telegram',
    'footer.telegramChannel': 'Telegram Channel',

    // Hero
    'hero.ministry': 'Yeka M.K.C Ministry',
    'hero.title': 'Yeka Meserete Kristos',
    'hero.subtitle': 'Discover choir songs, worship music, and worship united by faith and community.',
    'hero.verse': 'LET EVERYTHING THAT HAS BREATH PRAISE THE LORD. PRAISE THE LORD! - PSALM 150:6',
    'hero.discoverSongs': 'Discover Songs',
    'hero.exploreChoir': 'Explore Choir',
    'hero.viewPerformances': 'Watch Worship',
    'hero.exploreSongs': 'Explore Songs',
    'hero.prevImage': 'Previous hero image',
    'hero.nextImage': 'Next hero image',
    'hero.showImage': 'Show hero image',

    // Home
    'home.welcome': 'Welcome back',
    'home.featuredSongs': 'Featured Songs',
    'home.musicLibrary': 'Music library',
    'home.viewAllSongs': 'View All Songs',
    'home.songAndChoir': 'Song and choir',
    'home.ethiopianScale': 'Ethiopian scale',
    'home.likes': 'Likes',
    'home.upcomingPerformances': 'Latest Worship',
    'home.liveWorship': 'Live worship',
    'home.noScheduled': 'No upcoming worship is scheduled.',
    'home.about': 'About the ministry',
    'home.aboutText': 'Yeka Meserete Kristos preserves and shares choir songs, worship, and worship resources for singers and listeners.',
    'home.aboutHeading': 'Music rooted in worship and community',
    'home.readMore': 'Read More',
    'home.locationTba': 'Location to be announced',
    'home.loginToLike': 'Login to like this song',
    'home.likeTitle': 'Like this song',
    'home.unlikeTitle': 'Unlike this song',
    'home.loginPromptTitle': 'Login to like this song',
    'home.loginPromptText': 'Sign in to save songs and add your like.',
    'home.login': 'Login',
    'home.cancel': 'Cancel',

    // Songs page
    'songs.title': 'Song Library',
    'songs.subtitle': 'Browse choir songs, worship music, and traditional melodies.',
    'songs.search': 'Search songs...',
    'songs.all': 'All',
    'songs.sortTitle': 'Sort by title',
    'songs.sortNewest': 'Newest first',
    'songs.sortPopular': 'Most liked',
    'songs.noResults': 'No songs found',
    'songs.noResultsText': 'Try adjusting your search or filters.',
    'songs.loading': 'Loading songs...',
    'songs.empty': 'No songs are available yet.',
    'songs.song': 'Song',
    'songs.createdBy': 'Created by',
    'songs.choir': 'Choir',
    'songs.scale': 'Scale',
    'songs.likes': 'Likes',
    'songs.actions': 'Actions',
    'songs.lyrics': 'Lyrics',
    'songs.audio': 'Audio',
    'songs.play': 'Play',
    'songs.pause': 'Pause',
    'songs.viewLyrics': 'View lyrics',
    'songs.loginToLike': 'Login to like this song',
    'songs.traditional': 'Traditional',
    'songs.like': 'Like',
    'songs.unlike': 'Unlike',
    'songs.viewSong': 'View Song',
    'songs.searchPlaceholder': 'Search songs by title, choir, or composer...',
    'songs.filterByChoir': 'Filter by Choir',
    'songs.allChoirs': 'All Choirs',
    'songs.sortSongs': 'Sort Songs',
    'songs.mostLiked': 'Most Liked (Popular)',
    'songs.newestFirst': 'Newest First',
    'songs.oldestFirst': 'Oldest First',
    'songs.titleAZ': 'Title (A - Z)',
    'songs.myLiked': 'My Liked Songs',
    'songs.resetFilters': 'Reset Filters',
    'songs.clearAllFilters': 'Clear All Filters',
    'songs.showing': 'Showing {{shown}} of {{total}} choir songs',
    'songs.filteredByLiked': 'Filtered by Liked Songs',
    'songs.noMatch': 'No songs match your criteria',
    'songs.noMatchText': 'Try clearing your search keyword or selecting a different choir.',
    'songs.updating': 'Our Ethiopian choir songs catalog is being updated. Please check back soon.',
    'songs.createdByChoir': 'Created by Choir',
    'songs.notSpecified': 'Not specified',

    // Song detail
    'song.backToSongs': 'Back to Songs',
    'song.share': 'Share',
    'song.copied': 'Link copied!',
    'song.lyricsChords': 'Lyrics & Chords',
    'song.lyricsLocked': 'Lyrics are available to registered members. Please sign in.',
    'song.signIn': 'Sign In',
    'song.register': 'Register',
    'song.downloadAudio': 'Download Audio',
    'song.playAudio': 'Play',
    'song.pauseAudio': 'Pause',
    'song.likedBy': 'likes',
    'song.key': 'Key',
    'song.scaleMode': 'Scale / Mode',
    'song.composer': 'Composer',
    'song.artist': 'Artist',
    'song.lyricsNotAvailable': 'Lyrics are not available for this song.',
    'song.chordNotation': 'Chords appear before each line, e.g. [C]. They transpose automatically.',
    'song.download': 'Download',
    'song.detailLoading': 'Loading Ethiopian choir song...',
    'song.notFoundTitle': 'This song could not be found.',
    'song.notFoundMessage': 'It may be private, unpublished, or removed.',
    'song.backToSongs': 'Back to Songs',
    'song.backToDiscover': 'Back to Discover Songs',
    'song.linkCopied': 'Link Copied!',
    'song.share': 'Share',
    'song.audienceLove': 'Audience Love',
    'song.like': 'like',
    'song.likes': 'likes',
    'song.liked': 'Liked',
    'song.likeSong': 'Like Song',
    'song.unlikeSong': 'Unlike song',
    'song.loginModalTitle': 'Sign in to like this song',
    'song.loginSaveStart': 'Create a free account or sign in to save',
    'song.loginSaveEnd': 'to your liked songs collection and support our choirs.',
    'song.ethiopianChoirSong': 'Ethiopian Choir Song',
    'song.createdBy': 'Created by:',
    'song.composer': 'Composer',
    'song.artistLead': 'Artist / Lead',
    'song.arranger': 'Arranger',
    'song.dateAdded': 'Date Added',
    'song.language': 'Language',
    'song.listenToTrack': 'Listen to Track',
    'song.downloadAudio': 'Download Audio',
    'song.aboutThisSong': 'About this song',
    'song.lyricsChords': 'Lyrics & Chords',
    'song.transposeHint': 'Adjust pitch transpose to fit your vocal range.',
    'song.downSemitone': 'Down a semitone',
    'song.upSemitone': 'Up a semitone',
    'song.resetTranspose': 'Reset transpose',
    'song.reset': 'Reset',
    'song.semitone': 'semitone',
    'song.semitones': 'semitones',
    'song.quickTranspose': 'Quick transpose:',
    'song.artistLabel': 'Artist:',
    'song.audioNotAvailable': 'Audio recording not available for this song.',
    'song.audioPreviewNotAvailable': 'Audio preview is not available for this song.',
    'song.lyricsHeading': 'Lyrics',

    // Performances
    'perf.title': 'Worship',
    'perf.subtitle': 'Live worship events, concerts, and choir worship.',
    'perf.upcoming': 'Upcoming',
    'perf.past': 'Past',
    'perf.all': 'All',
    'perf.noUpcoming': 'No upcoming worship is scheduled yet.',
    'perf.noUpcomingHint': 'New events will appear here once announced.',
    'perf.choir': 'Choir',
    'perf.location': 'Location',
    'perf.date': 'Worship Date',
    'perf.viewPerformance': 'Worship Details',
    'perf.status.upcoming': 'Upcoming',
    'perf.status.confirmed': 'Confirmed',
    'perf.status.completed': 'Completed',
    'perf.status.cancelled': 'Cancelled',
    'perf.status.postponed': 'Postponed',
    'perf.lastUpdated': 'last updated',
    'perf.viewEvent': 'View Event',
    'perf.dateUnavailable': 'Date unavailable',
    'perf.heroBadge': 'Choir Worship Schedule',
    'perf.heroTitle': 'Choir Worship Programs',
    'perf.heroSubtitle': 'Experience Ethiopian choral worship, seasonal musical events, concerts, and Sunday presentations across our community.',
    'perf.tabUpcoming': 'Upcoming Worship',
    'perf.tabPast': 'Past Worship',
    'perf.searchPlaceholder': 'Search programs, events, venues...',
    'perf.allTypes': 'All Program Types',
    'perf.tWorship': 'Worship',
    'perf.tWorshipNight': 'Worship Night',
    'perf.tConcert': 'Concert',
    'perf.tSpecial': 'Special Program',
    'perf.tSunday': 'Sunday Service',
    'perf.tChristmas': 'Christmas',
    'perf.tEaster': 'Easter',
    'perf.tYouth': 'Youth',
    'perf.tPresentation': 'Choir Presentation',
    'perf.tOther': 'Other',
    'perf.featured': 'Featured Program',
    'perf.by': 'By',
    'perf.time': 'Time',
    'perf.locationVenue': 'Location / Venue',
    'perf.viewProgram': 'View Program & Songs',
    'perf.piecesScheduled': '{{count}} musical pieces scheduled',
    'perf.worshipPresentation': 'Worship presentation',
    'perf.emptyUpcomingTitle': 'No Upcoming Worship Found',
    'perf.emptyUpcomingMessage': 'There are currently no upcoming choir worship scheduled. Please check back soon or explore past archives.',
    'perf.emptyPastTitle': 'No Past Worship Found',
    'perf.emptyPastMessage': 'No past worship match your search criteria.',
    'perf.eyebrowMore': 'More Schedule',
    'perf.eyebrowArchive': 'Archive',
    'perf.upcomingPrograms': 'Upcoming Programs ({{count}})',
    'perf.pastPrograms': 'Past Programs ({{count}})',
    'perf.upcomingGridSubtitle': 'Join us for these upcoming choir worship presentations and events.',
    'perf.archiveSubtitle': 'Archive of choir presentations, concerts, and worship services.',

    // Performance detail
    'perfDetail.back': 'Back to Worship',
    'perfDetail.songsInProgram': 'Songs in the Program',
    'perfDetail.noSongs': 'No songs have been added to this worship yet.',
    'perfDetail.lyricsPreview': 'Lyrics Preview',
    'perfDetail.locationTba': 'Location to be announced',
    'perfDetail.addToCalendar': 'Add to Calendar',
    'perfDetail.notFoundTitle': 'Program Not Found',
    'perfDetail.notFoundMessage': 'This worship program may be private, cancelled, or does not exist.',
    'perfDetail.backToUpcoming': 'Back to Upcoming Programs',
    'perfDetail.venueLocation': 'Venue / Location',
    'perfDetail.overview': 'Program Overview',
    'perfDetail.organizedBy': 'Organized By',
    'perfDetail.dressCode': 'Dress Code',
    'perfDetail.specialInstructions': 'Special Instructions',
    'perfDetail.assignedSongs': 'Assigned Program Songs',
    'perfDetail.songsSubtitle': 'Musical pieces scheduled for this worship presentation.',
    'perfDetail.songSingle': 'Song',
    'perfDetail.songPlural': 'Songs',
    'perfDetail.noSongsAssigned': 'No songs currently assigned.',
    'perfDetail.setlistHint': 'The choir leadership will update the setlist before the event.',
    'perfDetail.bySong': 'By {{name}}',
    'perfDetail.songDetails': 'Song Details',

    // Choirs
    'choirs.title': 'Our Choirs',
    'choirs.subtitle': 'Meet the choirs and worship teams of Yeka Meserete Kristos.',
    'choirs.noChoirs': 'No choirs are available yet.',
    'choirs.viewChoir': 'View Choir',
    'choirs.explore': 'Explore',
    'choirs.eyebrow': 'Community',
    'choirs.heroSubtitle': 'Discover the voices, people, and stories behind YKA M.K.C Choirs and Worship Teams.',
    'choirs.searchPlaceholder': 'Search choirs by name or leader',
    'choirs.searchAria': 'Search choirs',
    'choirs.loading': 'Loading choirs...',
    'choirs.noMatch': 'No choirs match "{{query}}".',
    'choirs.checkBack': 'Check back soon as our choirs continue to grow.',

    // Choir detail
    'choir.members': 'Members',
    'choir.member': 'Member',
    'choir.leader': 'Leader',
    'choir.viewHistory': 'View History',
    'choir.estYear': 'Founded',
    'choir.established': 'Established',
    'choir.moreSongs': 'More songs can be found in the choir library.',
    'choir.songs': 'Songs',
    'choir.noSongs': 'No songs have been added to this choir yet.',
    'choir.history': 'History',
    'choir.ledBy': 'Led by {{name}}',
    'choir.memberCount': '{{count}} members',
    'choir.performances': 'Worship',
    'choir.loading': 'Loading choir...',
    'choir.notFoundTitle': 'This choir could not be found.',
    'choir.notFoundMessage': 'It may be private or no longer available.',
    'choir.backToChoirs': 'Back to Choirs',
    'choir.allChoirs': 'All Choirs',
    'choir.tabOverview': 'Overview',
    'choir.tabSongs': 'Songs',
    'choir.tabPerformances': 'Worship',
    'choir.tabGallery': 'Gallery',
    'choir.tabMembers': 'Members',
    'choir.tabAnnouncements': 'Announcements',
    'choir.noSongsPublished': 'No songs published yet.',
    'choir.noSongsPublishedMsg': 'This choir has not shared songs publicly.',
    'choir.upcomingCount': 'Upcoming ({{count}})',
    'choir.noUpcoming': 'No upcoming worship.',
    'choir.noUpcomingMsg': 'Check back soon for the next gathering.',
    'choir.pastPerformances': 'Past Worship',
    'choir.noPast': 'No past worship recorded.',
    'choir.noGallery': 'No gallery photos yet.',
    'choir.noGalleryMsg': 'Moments from this choir will appear here.',
    'choir.noMembersListed': 'No members are publicly listed.',
    'choir.noMembersListedMsg': 'Member profiles for this choir are private.',
    'choir.noAnnouncements': 'No announcements yet.',
    'choir.noAnnouncementsMsg': 'Updates from this choir will appear here.',
    'choir.aboutThisChoir': 'About this Choir',
    'choir.aboutFallback': 'A vibrant part of the YKA M.K.C Choirs and Worship Teams community.',
    'choir.nextPerformance': 'Next Worship',
    'choir.latestSongs': 'Latest Songs',
    'choir.leaderLabel': 'Choir Leader',
    'choir.latestAnnouncement': 'Latest Announcement',

    // History
    'history.heritage': 'Heritage',
    'history.title': 'Our History',
    'history.subtitle': 'A journey of worship, service, and song. Explore the milestones and memories that have shaped YKA M.K.C Choirs and Worship Teams through the years.',
    'history.loading': 'Loading history...',
    'history.emptyTitle': 'Our history is just beginning.',
    'history.emptyMessage': 'Once worship concludes, they will be remembered here. Check back soon.',
    'history.pastPerformances': 'Past Worship',
    'history.yearsOfWorship': 'Years of Worship',
    'history.timelineEyebrow': 'Timeline',
    'history.timelineTitle': 'Moments We Cherish',
    'history.timelineSubtitle': 'Each year, a story of faithful voices coming together.',
    'history.performancesOne': 'Worship',
    'history.performancesMany': 'Worship',

    // Choir history (landing)
    'choirHistory.notFoundTitle': 'Choir not found',
    'choirHistory.backToChoirs': 'Back to choirs',
    'choirHistory.history': 'History',
    'choirHistory.timeline': 'Timeline',
    'choirHistory.photos': 'Historical Photos',
    'choirHistory.performances': 'Important Worship',
    'choirHistory.noPerformances': 'No public worship yet.',

    // About
    'about.title': 'About Yeka Meserete Kristos',
    'about.paragraph1': 'Yeka Meserete Kristos Church is a fellowship of believers worshipping God in spirit and in truth.',
    'about.paragraph2': 'Our choir ministry exists to lead worship, preserve Ethiopian sacred music, and build community through song.',
    'about.paragraph3': 'This music archive keeps our songs, worship, and history alive for the next generation.',
    'about.pastoralMessage': 'Pastoral Message',
    'about.exploreSongs': 'Explore Choir Songs',
    'about.eyebrow': 'About Us',
    'about.pastor': 'Pastor',
    'about.pastorMessage': 'Add a short message from the pastor here. This space can introduce the church, welcome visitors, and share a word about the choir ministry.',

    // Calendar / common
    'common.loading': 'Loading...',
    'common.previous': 'Previous',
    'common.next': 'Next',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.search': 'Search',
    'common.filters': 'Filters',
    'common.all': 'All',
    'common.noResults': 'No results found.',
    'common.viewAll': 'View All',
    'common.items': 'items',
    'common.showingRange': 'Showing {{start}} to {{end}} of {{total}} {{itemName}}',
    'common.back': 'Back',
    'common.backToHome': 'Back to home',
    'common.switchLanguage': 'Switch language',
    'common.language': 'Language',
    'common.showPassword': 'Show password',
    'common.hidePassword': 'Hide password',
    'common.today': 'Today',
    'common.performance': 'Worship',
    'common.performanceDate': 'Worship Date',
    'common.performanceDetails': 'Worship Details',
    'common.rehearsal': 'Rehearsal',
    'common.readLyrics': 'Read Lyrics',
    'common.memberLogin': 'Member Login',
    'common.signIn': 'Sign In',
    'common.monthNames': ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    'common.monthShort': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    'common.dayNames': ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    'common.weekdayNames': ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],

    // Member / Navigation / Dashboard / Common additional keys
    'dashboard.portal': 'Member Portal',
    'dashboard.welcome_back': 'Welcome back, {{name}}!',
    'dashboard.load_error': 'Could not load dashboard',
    'dashboard.not_assigned_choir': 'You are not assigned to a choir yet.',
    'dashboard.no_choir_message': 'Once an administrator assigns you to a choir, your schedule, worship and attendance will appear here.',
    'choir.not_assigned_title': 'No choir assigned',
    'dashboard.upcoming_performances': 'Latest Worship',
    'dashboard.upcoming_rehearsals': 'Upcoming Practice',
    'dashboard.scheduled_ahead': 'Scheduled ahead',
    'dashboard.attendance': 'Attendance',
    'dashboard.attendance_hint': '{{absent}} absent, {{late}} late',
    'dashboard.no_records_yet': 'No records yet',
    'dashboard.my_performances': 'My Worship',
    'dashboard.scheduled_count': 'You are scheduled',
    'dashboard.upcoming_performance': 'Latest Worship',
    'dashboard.no_upcoming_performances': 'No upcoming worship.',
    'dashboard.next_rehearsal': 'Next Practice',
    'dashboard.no_upcoming_rehearsals': 'No upcoming practice.',
    'dashboard.no_performance_participation': 'No worship participation yet.',

    'nav.members': 'Members',
    'nav.rehearsals': 'Practice',
    'nav.calendar': 'Calendar',
    'nav.users': 'Users',
    'nav.roles_permissions': 'Roles & Permissions',
    'nav.reports': 'Reports',
    'nav.activity_logs': 'Activity Logs',
    'nav.section.organization': 'Organization',
    'nav.section.content': 'Content',
    'nav.section.schedule': 'Schedule',
    'nav.section.user_management': 'User Management',
    'nav.section.reports': 'Reports',
    'nav.section.system': 'System',
    'nav.section.my_choir': 'My Choir',
    'nav.section.music': 'Music',
    'nav.section.ministry': 'Ministry',
    'nav.section.my_participation': 'My Participation',
    'nav.section.account': 'Account',
    'nav.my_attendance': 'My Attendance',
    'nav.choir_history': 'Choir History',
    'nav.my_profile': 'My Profile',
    'nav.sign_out': 'Sign Out',
    'nav.settings': 'Settings',

    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.retry': 'Retry',
    'common.noData': 'No data found',
    'common.tbd': 'TBD',

    'header.open_nav': 'Open navigation',
    'header.close_nav': 'Close navigation',
    'header.all_choirs': 'All Choirs',
    'header.global_overview': 'Global Overview',
    'header.no_choir': 'No Choir',
    'header.not_assigned': 'Not assigned',
    'header.switch_to_light': 'Switch to light mode',
    'header.switch_to_dark': 'Switch to dark mode',
    'header.light_mode': 'Light Mode',
    'header.dark_mode': 'Dark Mode',
    'header.notifications': 'Notifications',
    'header.new_count': '{{count}} new',
    'header.mark_all_read': 'Mark all as read',
    'header.no_notifications': 'No notifications',
    'header.all_caught_up': "You're all caught up with choir updates.",

    'role.member': 'Member',
    'role.team_leader': 'Team Leader',
    'role.musician': 'Musician',
    'role.admin': 'Admin',
    'role.super_admin': 'Super Admin',
    'dashboard.musician_portal': 'Musician Portal',

    // Auth
    'auth.loginTitle': 'Welcome back',
    'auth.loginSubtitle': 'Sign in to access your choir account.',
    'auth.registerTitle': 'Create your account',
    'auth.registerSubtitle': 'Join the choir community.',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': "Don't have an account?",
    'auth.yesAccount': 'Already have an account?',
    'auth.submitLogin': 'Sign In',
    'auth.submitRegister': 'Register',
    'auth.memberTagline': 'Choirs & Worship Teams',
    'auth.emailAddress': 'Email Address',
    'auth.remember': 'Keep me signed in',
    'auth.requestAccess': 'Request Access',
    'auth.loginFailed': 'Login failed. Please check your credentials.',
    'auth.fullName': 'Full Name',
    'auth.phone': 'Phone',
    'auth.phoneHint': '9 digits, starting with 9 (e.g. 912345678)',
    'auth.chooseChoir': 'Choose Choir',
    'auth.loadingChoirs': 'Loading choirs...',
    'auth.confirmPassword': 'Confirm Password',
    'auth.registerAsMember': 'Register as a choir member. Administrator approval is required before access.',
    'auth.registerFailed': 'Registration failed. Please review the form.',
    'auth.pleaseSelectChoir': 'Please select a choir.',
    'auth.pendingApproval': 'Pending Approval',
    'auth.registrationSubmitted': 'Registration Submitted',
    'auth.thankYou': 'Thank you, {{name}}!',
    'auth.waitingApproval': 'Your account is currently waiting for administrator approval.',
    'auth.reviewText': 'An administrator will review your registration and choir assignment. Once approved, you will be able to sign in with {{email}}.',
    'auth.yourEmail': 'your email',
    'auth.backToLogin': 'Back to Login',
};

const translationsAm = {
    // Navigation
    'nav.home': 'መነሻ',
    'nav.songs': 'መዝሙሮች',
    'nav.performances': 'የአምልኮ አገልግሎቶች',
    'nav.choirs': 'የመዘምራን ቡድኖች',
    'nav.about': 'ስለ እኛ',
    'nav.login': 'ግባ',
    'nav.register': 'ተመዝገብ',
    'nav.dashboard': 'ዳሽቦርድ',
    'nav.openMenu': 'ምናሌን ክፈት',
    'nav.closeMenu': 'ምናሌን ዝጋ',
    'nav.memberArea': 'የአባላት ክፍል',

    // Brand
    'brand.choirPrimary': 'የካ',
    'brand.choirSuffix': 'መዘምራን',
    'brand.choirName': 'የካ መሰረተ ክርስቶስ ቤተክርስትያት መዘምራን',

    // Footer
    'footer.tagline': 'ለየካ መሰረተ ክርስቶስ ቤተክርስትያት መዝሙር፣ መንፈሳዊ ሙዚቃና አምልኮ የዲጂታል ማዕከል።',
    'footer.quickLinks': 'ፈጣን አገናኞች',
    'footer.contact': 'ያግኙን',
    'footer.rights': 'ሁሉም መብቶች የተጠበቁ ናቸው።',
    'footer.history': 'ታሪክ',
    'footer.emailUs': 'ኢሜይል ይላኩ',
    'footer.website': 'ድረ-ገጽ',
    'footer.telegram': 'ቴሌግራም',
    'footer.telegramChannel': 'የቴሌግራም ቻናል',

    // Hero
    'hero.ministry': 'የካ መ.ክ.ቤ አገልግሎት',
    'hero.title': 'የካ መሰረተ ክርስቶስ ቤተክርስትያት',
    'hero.subtitle': 'በእምነትና በማህበረሰብ የተቆራኙ የዘማሪያን መዝሙሮችን፣ የአምልኮ ሙዚቃዎችንና መንፈሳዊ የአምልኮ ግብዓቶችን ያግኙ።',
    'hero.verse': 'ትንፋሽ ያለው ሁሉ እግዚአብሔርን ያመስግን! - መዝሙር 150፡6',
    'hero.discoverSongs': 'መዝሙሮች ያግኙ',
    'hero.exploreChoir': 'ቡድን ይመልከቱ',
    'hero.viewPerformances': 'የአምልኮ አገልግሎቶችን ይመልከቱ',
    'hero.exploreSongs': 'መዝሙሮችን ያስሱ',
    'hero.prevImage': 'ቀዳሚ ምስል',
    'hero.nextImage': 'ቀጣይ ምስል',
    'hero.showImage': 'ምስል ያሳይ',

    // Home
    'home.welcome': 'እንኳን ደህና መጡ',
    'home.featuredSongs': 'የተመረጡ መዝሙሮች',
    'home.musicLibrary': 'የሙዚቃ ቤተ-መዛግብት',
    'home.viewAllSongs': 'ሁሉንም መዝሙሮች ይመልከቱ',
    'home.songAndChoir': 'መዝሙርና ቡድን',
    'home.ethiopianScale': 'የኢትዮጵያ ቅጥ',
    'home.likes': 'መውደዶች',
    'home.upcomingPerformances': 'የመጪ የአምልኮ አገልግሎቶች',
    'home.liveWorship': 'ሕያው አምልኮ',
    'home.noScheduled': 'እስካሁን የመጪ የአምልኮ አገልግሎቶች አልተያዙም።',
    'home.about': 'ስለ አገልግሎቱ',
    'home.aboutText': 'የካ መሰረተ ክርስቶስ ቤተክርስትያት የመዘምራን መዝሙሮችን፣ የአምልኮ ሙዚቃንና መንፈሳዊ የአምልኮ ግብዓቶችን ይጠብቃል ያጋራልም።',
    'home.aboutHeading': 'በአምልኮና በማህበረሰብ የተመሰረተ ሙዚቃ',
    'home.readMore': 'ተጨማሪ ያንብቡ',
    'home.locationTba': 'ቦታ በኋላ ይገለጻል',
    'home.loginToLike': 'መውደድ እንዲችሉ ይግቡ',
    'home.likeTitle': 'ይህን መዝሙር ውደድ',
    'home.unlikeTitle': 'መውደድ አስቀር',
    'home.loginPromptTitle': 'መውደድ እንዲችሉ ይግቡ',
    'home.loginPromptText': 'መዝሙሮችን ለማስቀመጥና ለመውደድ ይግቡ።',
    'home.login': 'ግባ',
    'home.cancel': 'ሰርዝ',

    // Songs page
    'songs.title': 'የመዝሙር ቤተ-መዛግብት',
    'songs.subtitle': 'የመዘምራን መዝሙሮችን፣ የአምልኮ ሙዚቃንና የባህል ዜማዎችን ያስሱ።',
    'songs.search': 'መዝሙሮችን ይፈልጉ...',
    'songs.all': 'ሁሉም',
    'songs.sortTitle': 'በርዕስ ይደልድሉ',
    'songs.sortNewest': 'አዲሶቹ መጀመሪያ',
    'songs.sortPopular': 'በጣም የተወደዱ',
    'songs.noResults': 'መዝሙሮች አልተገኙም',
    'songs.noResultsText': 'ፍለጋዎን ወይም ማጣሪያዎን ለማስተካከል ይሞክሩ።',
    'songs.loading': 'መዝሙሮች በመጫን ላይ...',
    'songs.empty': 'እስካሁን ምንም መዝሙር የለም።',
    'songs.song': 'መዝሙር',
    'songs.createdBy': 'የፃፈው',
    'songs.choir': 'ቡድን',
    'songs.scale': 'ቅጥ',
    'songs.likes': 'መውደዶች',
    'songs.actions': 'ድርጊቶች',
    'songs.lyrics': 'ግጥም',
    'songs.audio': 'ድምጽ',
    'songs.play': 'አጫውት',
    'songs.pause': 'አቁም',
    'songs.viewLyrics': 'ግጥሙን ይመልከቱ',
    'songs.loginToLike': 'መውደድ እንዲችሉ ይግቡ',
    'songs.traditional': 'ባህላዊ',
    'songs.like': 'ወድጄዋለሁ',
    'songs.unlike': 'አስቀር',
    'songs.viewSong': 'መዝሙሩን ይመልከቱ',
    'songs.searchPlaceholder': 'በርዕስ፣ በቡድን ወይም በአቀናባሪ መዝሙሮችን ይፈልጉ...',
    'songs.filterByChoir': 'በቡድን አጣራ',
    'songs.allChoirs': 'ሁሉም ቡድኖች',
    'songs.sortSongs': 'መዝሙሮችን ደርድር',
    'songs.mostLiked': 'በጣም የተወደዱ',
    'songs.newestFirst': 'አዲሶቹ መጀመሪያ',
    'songs.oldestFirst': 'የቆዩት መጀመሪያ',
    'songs.titleAZ': 'ርዕስ (ሀ - ፐ)',
    'songs.myLiked': 'የወደድኳቸው መዝሙሮች',
    'songs.resetFilters': 'ማጣሪያዎችን ዳግም አስጀምር',
    'songs.clearAllFilters': 'ሁሉንም ማጣሪያዎች አጽዳ',
    'songs.showing': 'የሚታዩት፡ {{shown}} ከ {{total}} የመዘምራን መዝሙሮች',
    'songs.filteredByLiked': 'የወደዱትን ያሳያል',
    'songs.noMatch': 'ከመስፈርቶችዎ ጋር የሚስማማ መዝሙር የለም',
    'songs.noMatchText': 'የፍለጋ ቃልዎን ለማንጻት ወይም ሌላ ቡድን ለመምረጥ ይሞክሩ።',
    'songs.updating': 'የኢትዮጵያ የመዘምራን መዝሙር ካታሎግ እየተዘመነ ነው። እባክዎ በቅርቡ ይመልሱ።',
    'songs.createdByChoir': 'የፈጠረው ቡድን',
    'songs.notSpecified': 'አልተገለጸም',

    // Song detail
    'song.backToSongs': 'ወደ መዝሙሮች ተመለስ',
    'song.share': 'አጋራ',
    'song.copied': 'አገናኝ ተቀድቷል!',
    'song.lyricsChords': 'ግጥም እና ኮርዶች',
    'song.lyricsLocked': 'ግጥሞች ለተመዘገቡ አባላት ብቻ ይገኛሉ። እባክዎ ይግቡ።',
    'song.signIn': 'ግባ',
    'song.register': 'ተመዝገብ',
    'song.downloadAudio': 'ድምጽ አውርድ',
    'song.playAudio': 'አጫውት',
    'song.pauseAudio': 'አቁም',
    'song.likedBy': 'መውደዶች',
    'song.key': 'ቅል',
    'song.scaleMode': 'ቅጥ',
    'song.composer': 'አቀናባሪ',
    'song.artist': 'አርቲስት/ቡድን',
    'song.lyricsNotAvailable': 'ለዚህ መዝሙር ግጥም አይገኝም።',
    'song.chordNotation': 'ኮርዶች ከእያንዳንዱ ረድፍ በፊት ይጻፋሉ፣ ለምሳሌ [C]። በራስ-ሰር አብረው ይስተካከላሉ።',
    'song.download': 'አውርድ',
    'song.detailLoading': 'የኢትዮጵያ የመዘምራን መዝሙር እየተጫነ ነው...',
    'song.notFoundTitle': 'ይህ መዝሙር አልተገኘም።',
    'song.notFoundMessage': 'ምናልባት የግል፣ ያልታተመ ወይም የተወገደ ነው።',
    'song.backToSongs': 'ወደ መዝሙሮች ተመለስ',
    'song.backToDiscover': 'ወደ መዝሙሮች ማግኛ ተመለስ',
    'song.linkCopied': 'ሊንክ ተገልብጧል!',
    'song.share': 'አጋራ',
    'song.audienceLove': 'የተመልካች ፍቅር',
    'song.like': 'መውደድ',
    'song.likes': 'መውደዶች',
    'song.liked': 'ወድጄዋለሁ',
    'song.likeSong': 'ወድጄዋለሁ',
    'song.unlikeSong': 'አይውደዱ',
    'song.loginModalTitle': 'ይህን መዝሙር ለመውደድ ይግቡ',
    'song.loginSaveStart': 'በነጻ መለያ ይፍጠሩ ወይም ይግቡና',
    'song.loginSaveEnd': 'ን ወደ እርስዎ የተወደዱ መዝሙሮች ስብስብ ለማከማቸት እና ቡድኖቻችንን ለመደገፍ።',
    'song.ethiopianChoirSong': 'የኢትዮጵያ የመዘምራን መዝሙር',
    'song.createdBy': 'የፈጠረው፡',
    'song.composer': 'አቀናባሪ',
    'song.artistLead': 'አርቲስት / መሪ',
    'song.arranger': 'ዝግጅት',
    'song.dateAdded': 'የተጨመረበት ቀን',
    'song.language': 'ቋንቋ',
    'song.listenToTrack': 'መዝሙሩን ያድምጡ',
    'song.downloadAudio': 'ድምጽ አውርድ',
    'song.aboutThisSong': 'ስለዚህ መዝሙር',
    'song.lyricsChords': 'ግጥም እና ዜማ',
    'song.transposeHint': 'ከድምጽ ቃናዎ ጋር ለማስማማት የቃናውን ደረጃ ያስተካክሉ።',
    'song.downSemitone': 'አንድ ሴሚቶን ዝቅ አድርግ',
    'song.upSemitone': 'አንድ ሴሚቶን ከፍ አድርግ',
    'song.resetTranspose': 'ቃናውን ዳግም አስጀምር',
    'song.reset': 'ዳግም አስጀምር',
    'song.semitone': 'ሴሚቶን',
    'song.semitones': 'ሴሚቶኖች',
    'song.quickTranspose': 'ፈጣን የቃና ለውጥ፡',
    'song.artistLabel': 'አርቲስት፡',
    'song.audioNotAvailable': 'ለዚህ መዝሙር የድምጽ ቀረጻ አይገኝም።',
    'song.audioPreviewNotAvailable': 'ለዚህ መዝሙር የድምጽ ቅድመ-እይታ አይገኝም።',
    'song.lyricsHeading': 'ግጥም',

    // Performances
    'perf.title': 'የአምልኮ አገልግሎቶች',
    'perf.subtitle': 'ሕያው የአምልኮ አገልግሎቶችና የመዘምራን የአምልኮ ፕሮግራሞች።',
    'perf.upcoming': 'የመጪ',
    'perf.past': 'ያለፉ',
    'perf.all': 'ሁሉም',
    'perf.noUpcoming': 'እስካሁን ምንም የመጪ የአምልኮ አገልግሎት አልተያዘም።',
    'perf.noUpcomingHint': 'አዳዲስ ዝግጅቶች ሲታወቁ እዚህ ይታያሉ።',
    'perf.choir': 'ቡድን',
    'perf.location': 'ቦታ',
    'perf.date': 'ቀን',
    'perf.viewPerformance': 'ፕሮግራሙን ይመልከቱ',
    'perf.status.upcoming': 'የመጪ',
    'perf.status.confirmed': 'የተረጋገጠ',
    'perf.status.completed': 'የተፈጸመ',
    'perf.status.cancelled': 'ተሰርዟል',
    'perf.status.postponed': 'ተላልፏል',
    'perf.lastUpdated': 'በመጨረሻ የተሻሻለ',
    'perf.viewEvent': 'ፕሮግራሙን ይመልከቱ',
    'perf.dateUnavailable': 'ቀን አይገኝም',
    'perf.heroBadge': 'የመዘምራን የአምልኮ መርሃ ግብር',
    'perf.heroTitle': 'የአምልኮ አገልግሎቶች እና ፕሮግራሞች',
    'perf.heroSubtitle': 'በማህበረሰባችን ውስጥ የኢትዮጵያ የመዘምራን አምልኮ፣ የእሑድ አገልግሎትና የበዓላት የአምልኮ ፕሮግራሞችን ይለማመዱ።',
    'perf.tabUpcoming': 'የመጪ የአምልኮ አገልግሎቶች',
    'perf.tabPast': 'ያለፉ የአምልኮ አገልግሎቶች',
    'perf.searchPlaceholder': 'ፕሮግራሞችን፣ ዝግጅቶችን፣ ቦታዎችን ይፈልጉ...',
    'perf.allTypes': 'ሁሉም የፕሮግራም ዓይነቶች',
    'perf.tWorship': 'አምልኮ',
    'perf.tWorshipNight': 'የአምልኮ ምሽት',
    'perf.tConcert': 'ኮንሰርት',
    'perf.tSpecial': 'ልዩ ፕሮግራም',
    'perf.tSunday': 'የእሑድ አገልግሎት',
    'perf.tChristmas': 'ገና',
    'perf.tEaster': 'ፋሲካ',
    'perf.tYouth': 'የወጣቶች',
    'perf.tPresentation': 'የመዘምራን አቀራረብ',
    'perf.tOther': 'ሌላ',
    'perf.featured': 'ዋና ፕሮግራም',
    'perf.by': 'ያቀረበው',
    'perf.time': 'ሰዓት',
    'perf.locationVenue': 'ቦታ / ቦታ',
    'perf.viewProgram': 'ፕሮግራም እና መዝሙሮችን ይመልከቱ',
    'perf.piecesScheduled': '{{count}} መዝሙሮች ተይዘዋል',
    'perf.worshipPresentation': 'የአምልኮ አቀራረብ',
    'perf.emptyUpcomingTitle': 'ምንም የመጪ የአምልኮ አገልግሎት አልተገኘም',
    'perf.emptyUpcomingMessage': 'እስካሁን የሚመጡ የመዘምራን የአምልኮ አገልግሎቶች አልተያዙም። እባክዎ በቅርቡ ይመልሱ ወይም ያለፉትን ያስሱ።',
    'perf.emptyPastTitle': 'ምንም ያለፈ የአምልኮ አገልግሎት አልተገኘም',
    'perf.emptyPastMessage': 'ከፍለጋ መስፈርቶችዎ ጋር የሚስማማ ያለፈ የአምልኮ አገልግሎት የለም።',
    'perf.eyebrowMore': 'ተጨማሪ መርሃ ግብር',
    'perf.eyebrowArchive': 'ቤተ መዛግብት',
    'perf.upcomingPrograms': 'የመጪ ፕሮግራሞች ({{count}})',
    'perf.pastPrograms': 'ያለፉ ፕሮግራሞች ({{count}})',
    'perf.upcomingGridSubtitle': 'ለእነዚህ የመጪ የመዘምራን አምልኮና ዝግጅቶች ይቀላቀሉን።',
    'perf.archiveSubtitle': 'የመዘምራን የአምልኮ አገልግሎቶችና ፕሮግራሞች ቤተ መዛግብት።',

    // Performance detail
    'perfDetail.back': 'ወደ የአምልኮ አገልግሎቶች ተመለስ',
    'perfDetail.songsInProgram': 'የፕሮግራም መዝሙሮች',
    'perfDetail.noSongs': 'ለዚህ ፕሮግራም እስካሁን ምንም መዝሙር አልተጨመረም።',
    'perfDetail.lyricsPreview': 'የግጥም ቅድመ-እይታ',
    'perfDetail.locationTba': 'ቦታ በኋላ ይገለጻል',
    'perfDetail.addToCalendar': 'ወደ መዝገበ ቀናት ጨምር',
    'perfDetail.notFoundTitle': 'ፕሮግራም አልተገኘም',
    'perfDetail.notFoundMessage': 'ይህ የአምልኮ ፕሮግራም የግል፣ የተሰረዘ ወይም የሌለ ሊሆን ይችላል።',
    'perfDetail.backToUpcoming': 'ወደ የመጪ ፕሮግራሞች ተመለስ',
    'perfDetail.venueLocation': 'ቦታ / ስፍራ',
    'perfDetail.overview': 'የፕሮግራም አጠቃላይ እይታ',
    'perfDetail.organizedBy': 'የሚያዘጋጀው',
    'perfDetail.dressCode': 'የአለባበስ ሥርዓት',
    'perfDetail.specialInstructions': 'ልዩ መመሪያዎች',
    'perfDetail.assignedSongs': 'የተመደቡ ፕሮግራም መዝሙሮች',
    'perfDetail.songsSubtitle': 'ለዚህ የአምልኮ ፕሮግራም የተያዙ መዝሙሮች።',
    'perfDetail.songSingle': 'መዝሙር',
    'perfDetail.songPlural': 'መዝሙሮች',
    'perfDetail.noSongsAssigned': 'እስካሁን ምንም መዝሙር አልተመደበም።',
    'perfDetail.setlistHint': 'የመዘምራን አመራር ከዝግጅቱ በፊት የመዝሙር ዝርዝሩን ያዘምናል።',
    'perfDetail.bySong': 'በ{{name}}',
    'perfDetail.songDetails': 'የመዝሙር ዝርዝር',

    // Choirs
    'choirs.title': 'የእኛ የመዘምራን ቡድኖች',
    'choirs.subtitle': 'የየካ መሰረተ ክርስቶስ ቤተክርስትያት የመዘምራን ቡድኖችንና የአምልኮ ቡድኖችን ይወቁ።',
    'choirs.noChoirs': 'እስካሁን ምንም የመዘምራን ቡድን የለም።',
    'choirs.viewChoir': 'ቡድኑን ይመልከቱ',
    'choirs.explore': 'ይቃኙ',
    'choirs.eyebrow': 'ማህበረሰብ',
    'choirs.heroSubtitle': 'ከየካ መሰረተ ክርስቶስ ቤተክርስትያት የመዘምራን ቡድኖችና የአምልኮ ቡድኖች ጀርባ ያሉትን ድምጾች፣ ሰዎችና ታሪኮች ይገኙ።',
    'choirs.searchPlaceholder': 'ቡድኖችን በስም ወይም በመሪ ይፈልጉ',
    'choirs.searchAria': 'ቡድኖችን ይፈልጉ',
    'choirs.loading': 'ቡድኖች በመጫን ላይ...',
    'choirs.noMatch': 'ከ«{{query}}» ጋር የሚስማማ ቡድን የለም።',
    'choirs.checkBack': 'ቡድኖቻችን እያደጉ ሲሄዱ በቅርቡ ይመልሱ።',

    // Choir detail
    'choir.members': 'አባላት',
    'choir.member': 'አባል',
    'choir.leader': 'መሪ',
    'choir.viewHistory': 'ታሪክን ይመልከቱ',
    'choir.estYear': 'የተመሰረተ',
    'choir.established': 'የተመሰረተበት',
    'choir.moreSongs': 'ተጨማሪ መዝሙሮች በቡድኑ ቤተ-መዛግብት ይገኛሉ።',
    'choir.songs': 'መዝሙሮች',
    'choir.noSongs': 'ለዚህ ቡድን እስካሁን ምንም መዝሙር አልተጨመረም።',
    'choir.history': 'ታሪክ',
    'choir.ledBy': 'በ{{name}} የሚመራ',
    'choir.memberCount': '{{count}} አባላት',
    'choir.performances': 'የአምልኮ አገልግሎቶች',
    'choir.loading': 'ቡድን በመጫን ላይ...',
    'choir.notFoundTitle': 'ይህ ቡድን አልተገኘም።',
    'choir.notFoundMessage': 'የግል ወይም የማይገኝ ሊሆን ይችላል።',
    'choir.backToChoirs': 'ወደ ቡድኖች ተመለስ',
    'choir.allChoirs': 'ሁሉም ቡድኖች',
    'choir.tabOverview': 'አጠቃላይ እይታ',
    'choir.tabSongs': 'መዝሙሮች',
    'choir.tabPerformances': 'የአምልኮ አገልግሎቶች',
    'choir.tabGallery': 'ማዕከለ-ስዕላት',
    'choir.tabMembers': 'አባላት',
    'choir.tabAnnouncements': 'ማስታወቂያዎች',
    'choir.noSongsPublished': 'እስካሁን ምንም መዝሙር አልታተመም።',
    'choir.noSongsPublishedMsg': 'ይህ ቡድን መዝሙሮቹን በይፋ አላጋራም።',
    'choir.upcomingCount': 'የመጪ ({{count}})',
    'choir.noUpcoming': 'ምንም የመጪ የአምልኮ አገልግሎት የለም።',
    'choir.noUpcomingMsg': 'ለቀጣዩ ስብሰባ በቅርቡ ይመልሱ።',
    'choir.pastPerformances': 'ያለፉ የአምልኮ አገልግሎቶች',
    'choir.noPast': 'ምንም ያለፈ የአምልኮ አገልግሎት አልተመዘገበም።',
    'choir.noGallery': 'እስካሁን ምንም ፎቶ የለም።',
    'choir.noGalleryMsg': 'የዚህ ቡድን ጊዜያት እዚህ ይታያሉ።',
    'choir.noMembersListed': 'ምንም አባል በይፋ አልተዘረዘረም።',
    'choir.noMembersListedMsg': 'የዚህ ቡድን የአባላት መገለጫዎች የግል ናቸው።',
    'choir.noAnnouncements': 'እስካሁን ምንም ማስታወቂያ የለም።',
    'choir.noAnnouncementsMsg': 'የዚህ ቡድን ዝማኔዎች እዚህ ይታያሉ።',
    'choir.aboutThisChoir': 'ስለዚህ ቡድን',
    'choir.aboutFallback': 'የየካ መሰረተ ክርስቶስ ቤተክርስትያት የመዘምራን ቡድኖችና የአምልኮ ቡድኖች ሕያው አካል።',
    'choir.nextPerformance': 'ቀጣይ የአምልኮ አገልግሎት',
    'choir.latestSongs': 'የቅርብ መዝሙሮች',
    'choir.leaderLabel': 'የቡድን መሪ',
    'choir.latestAnnouncement': 'የቅርብ ማስታወቂያ',

    // History
    'history.heritage': 'ቅርስ',
    'history.title': 'ታሪካችን',
    'history.subtitle': 'የአምልኮ፣ የአገልግሎትና የዜማ ጉዞ። የየካ መሰረተ ክርስቶስ ቤተክርስትያት የመዘምራን ቡድኖችንና የአምልኮ ቡድኖችን በዓመታት የቀረጹ ክንውኖችንና ትዝታዎችን ያስሱ።',
    'history.loading': 'ታሪክ በመጫን ላይ...',
    'history.emptyTitle': 'ታሪካችን ገና እየጀመረ ነው።',
    'history.emptyMessage': 'የአምልኮ መርሃ ግብሮች እንዳለቁ እዚህ ይታወሳሉ። በቅርቡ ይመልሱ።',
    'history.pastPerformances': 'ያለፉ የአምልኮ አገልግሎቶች',
    'history.yearsOfWorship': 'የአምልኮ ዓመታት',
    'history.timelineEyebrow': 'የጊዜ መስመር',
    'history.timelineTitle': 'የምንወዳቸው ጊዜያት',
    'history.timelineSubtitle': 'በየዓመቱ የታማኝ ድምጾች አንድነት ታሪክ።',
    'history.performancesOne': 'የአምልኮ አገልግሎት',
    'history.performancesMany': 'የአምልኮ አገልግሎቶች',

    // Choir history (landing)
    'choirHistory.notFoundTitle': 'ቡድን አልተገኘም',
    'choirHistory.backToChoirs': 'ወደ ቡድኖች ተመለስ',
    'choirHistory.history': 'ታሪክ',
    'choirHistory.timeline': 'የጊዜ መስመር',
    'choirHistory.photos': 'ታሪካዊ ፎቶዎች',
    'choirHistory.performances': 'ጉልህ የአምልኮ መርሃ ግብሮች',
    'choirHistory.noPerformances': 'እስካሁን ምንም የህዝብ የአምልኮ አገልግሎት የለም።',

    // About
    'about.title': 'ስለ የካ መሰረተ ክርስቶስ ቤተክርስትያት',
    'about.paragraph1': 'የካ መሰረተ ክርስቶስ ቤተክርስትያት በመንፈስና በእውነት እግዚአብሔርን የምታመልክ የአማኞች ማህበረሰብ ናት።',
    'about.paragraph2': 'የእኛ የመዘምራን አገልግሎት አምልኮን ለመምራት፣ የኢትዮጵያ ቅዱስ ሙዚቃን ለመጠበቅና ማህበረሰብን በዜማ ለማጠናከር ይገለገላል።',
    'about.paragraph3': 'ይህ የሙዚቃ መዝገብ መዝሙሮቻችንን፣ የአምልኮ መርሃ ግብሮቻችንንና ታሪካችንን ለቀጣዩ ትውልድ ያስቀምጣል።',
    'about.pastoralMessage': 'የእረኛ መልእክት',
    'about.exploreSongs': 'የመዘምራን መዝሙሮች ያስሱ',
    'about.eyebrow': 'ስለ እኛ',
    'about.pastor': 'እረኛ',
    'about.pastorMessage': 'ከእረኛው አጭር መልእክት እዚህ ይጨምሩ። ይህ ቦታ ቤተክርስቲያኑን ማስተዋወቅ፣ ጎብኚዎችን መቀበልና ስለ መዘምራን አገልግሎት አንድ ቃል ማካፈል ይችላል።',

    // Calendar / common
    'common.loading': 'በመጫን ላይ...',
    'common.previous': 'ቀዳሚ',
    'common.next': 'ቀጣይ',
    'common.close': 'ዝጋ',
    'common.save': 'አስቀምጥ',
    'common.cancel': 'ሰርዝ',
    'common.search': 'ፈልግ',
    'common.filters': 'ማጣሪያዎች',
    'common.all': 'ሁሉም',
    'common.noResults': 'ምንም ውጤት አልተገኘም።',
    'common.viewAll': 'ሁሉንም ይመልከቱ',
    'common.items': 'ዕቃዎች',
    'common.showingRange': 'ከ{{total}} {{itemName}} ውስጥ {{start}} - {{end}} እየታዩ ናቸው',
    'common.back': 'ተመለስ',
    'common.backToHome': 'ወደ መነሻ ተመለስ',
    'common.switchLanguage': 'ቋንቋ ቀይር',
    'common.language': 'ቋንቋ',
    'common.showPassword': 'የይለፍ ቃል አሳይ',
    'common.hidePassword': 'የይለፍ ቃል ደብቅ',
    'common.today': 'ዛሬ',
    'common.performance': 'የአምልኮ አገልግሎት',
    'common.rehearsal': 'ልምምድ',
    'common.readLyrics': 'ግጥም ያንብቡ',
    'common.memberLogin': 'የአባላት መግቢያ',
    'common.signIn': 'ግባ',
    'common.monthNames': ['ጃንዋሪ', 'ፌብሩዋሪ', 'ማርች', 'ኤፕሪል', 'ሜይ', 'ጁን', 'ጁላይ', 'ኦገስት', 'ሴፕቴምበር', 'ኦክቶበር', 'ኖቬምበር', 'ዲሴምበር'],
    'common.monthShort': ['ጃን', 'ፌብ', 'ማር', 'ኤፕ', 'ሜይ', 'ጁን', 'ጁላ', 'ኦገ', 'ሴፕ', 'ኦክ', 'ኖቭ', 'ዲሴ'],
    'common.dayNames': ['እሑድ', 'ሰኞ', 'ማክሰ', 'ረቡዕ', 'ሐሙስ', 'አርብ', 'ቅዳሜ'],
    'common.weekdayNames': ['እሑድ', 'ሰኞ', 'ማክሰኞ', 'ረቡዕ', 'ሐሙስ', 'አርብ', 'ቅዳሜ'],

    // Member / Navigation / Dashboard / Common additional keys
    'dashboard.portal': 'የአባላት ፖርታል',
    'dashboard.welcome_back': 'እንኳን ደህና መጡ፣ {{name}}!',
    'dashboard.load_error': 'ዳሽቦርድ መጫን አልተቻለም',
    'dashboard.not_assigned_choir': 'እስካሁን ለየትኛውም ቡድን አልተመደቡም።',
    'dashboard.no_choir_message': 'አስተዳዳሪው ወደ ቡድን ሲመድብዎ መርሃ ግብርዎ፣ አምልኮዎ እና መገኘትዎ እዚህ ይታያሉ።',
    'choir.not_assigned_title': 'ቡድን አልተመደበም',
    'dashboard.upcoming_performances': 'የቅርብ ጊዜ አምልኮ',
    'dashboard.upcoming_rehearsals': 'የመጪ ልምምዶች',
    'dashboard.scheduled_ahead': 'წინ አስቀድሞ የተያዘ',
    'dashboard.attendance': 'የመገኘት መዝገብ',
    'dashboard.attendance_hint': '{{absent}} ቀሪ፣ {{late}} ዘግይቷል',
    'dashboard.no_records_yet': 'እስካሁን ምንም መዝገብ የለም',
    'dashboard.my_performances': 'የእኔ አምልኮ',
    'dashboard.scheduled_count': 'ተመድበዋል',
    'dashboard.upcoming_performance': 'የቅርብ ጊዜ አምልኮ',
    'dashboard.no_upcoming_performances': 'ምንም የመጪ አምልኮ የለም።',
    'dashboard.next_rehearsal': 'ቀጣይ ልምምድ',
    'dashboard.no_upcoming_rehearsals': 'ምንም የመጪ ልምምድ የለም።',
    'dashboard.no_performance_participation': 'እስካሁን ምንም የአምልኮ ተሳትፎ የለም።',

    'nav.members': 'አባላት',
    'nav.rehearsals': 'ልምምድ',
    'nav.calendar': 'የመዝገበ ቀናት',
    'nav.users': 'ተጠቃሚዎች',
    'nav.roles_permissions': 'ሚናዎች እና ፈቃዶች',
    'nav.reports': 'ዘገባዎች',
    'nav.activity_logs': 'የእንቅስቃሴ መዝገቦች',
    'nav.section.organization': 'ድርጅት',
    'nav.section.content': 'ይዘት',
    'nav.section.schedule': 'መርሃ ግብር',
    'nav.section.user_management': 'የተጠቃሚ አስተዳደር',
    'nav.section.reports': 'ዘገባዎች',
    'nav.section.system': 'ስርዓት',
    'nav.section.my_choir': 'የእኔ ቡድን',
    'nav.section.music': 'ሙዚቃ',
    'nav.section.ministry': 'አገልግሎት',
    'nav.section.my_participation': 'የእኔ ተሳትፎ',
    'nav.section.account': 'መለያ',
    'nav.my_attendance': 'የእኔ መገኘት',
    'nav.choir_history': 'የመዘምራን ታሪክ',
    'nav.my_profile': 'የእኔ መገለጫ',
    'nav.sign_out': 'ውጣ',
    'nav.settings': 'ቅንብሮች',

    'common.edit': 'አርትዕ',
    'common.delete': 'ሰርዝ',
    'common.view': 'ይመልከቱ',
    'common.retry': 'እንደገና ሞክር',
    'common.noData': 'ምንም መረጃ አልተገኘም',
    'common.tbd': 'በኋላ ይወሰናል',

    'header.open_nav': 'ምናሌ ክፈት',
    'header.close_nav': 'ምናሌ ዝጋ',
    'header.all_choirs': 'ሁሉም መዘምራን',
    'header.global_overview': 'አጠቃላይ እይታ',
    'header.no_choir': 'ምንም ቡድን የለም',
    'header.not_assigned': 'ያልተመደበ',
    'header.switch_to_light': 'ወደ ብርሃን ገጽታ ቀይር',
    'header.switch_to_dark': 'ወደ ጨለማ ገጽታ ቀይር',
    'header.light_mode': 'ብርሃን ገጽታ',
    'header.dark_mode': 'ጨለማ ገጽታ',
    'header.notifications': 'ማሳወቂያዎች',
    'header.new_count': '{{count}} አዲስ',
    'header.mark_all_read': 'ሁሉንም እንደተነበበ ምልክት አድርግ',
    'header.no_notifications': 'ምንም ማሳወቂያ የለም',
    'header.all_caught_up': 'የመዘምራን ዝማኔዎች ተጠናቀዋል።',

    'role.member': 'አባል',
    'role.team_leader': 'የቡድን መሪ',
    'role.musician': 'ሙዚቀኛ',
    'role.admin': 'አስተዳዳሪ',
    'role.super_admin': 'ዋና አስተዳዳሪ',
    'dashboard.musician_portal': 'የሙዚቀኞች ፖርታል',

    // Auth
    'auth.loginTitle': 'እንኳን ደህና መጡ',
    'auth.loginSubtitle': 'የዘማሪነት መለያዎን ለማግኘት ይግቡ።',
    'auth.registerTitle': 'መለያ ይፍጠሩ',
    'auth.registerSubtitle': 'ከመዘምራን ማህበረሰብ ጋር ይተባበሩ።',
    'auth.email': 'ኢሜይል',
    'auth.password': 'የይለፍ ቃል',
    'auth.forgotPassword': 'የይለፍ ቃል ረሱ?',
    'auth.noAccount': 'መለያ የሎትም?',
    'auth.yesAccount': 'መለያ አለዎት?',
    'auth.submitLogin': 'ግባ',
    'auth.submitRegister': 'ተመዝገብ',
    'auth.memberTagline': 'የመዘምራን ቡድኖች እና የአምልኮ ቡድኖች',
    'auth.emailAddress': 'ኢሜይል አድራሻ',
    'auth.remember': 'መግቢያዬን አስታውስ',
    'auth.requestAccess': 'መግቢያ ይጠይቁ',
    'auth.loginFailed': 'መግባት አልተሳካም። እባክዎ መረጃዎን ያረጋግጡ።',
    'auth.fullName': 'ሙሉ ስም',
    'auth.phone': 'ስልክ',
    'auth.phoneHint': '9 አሃዝ፣ በ9 የሚጀምር (ለምሳሌ 912345678)',
    'auth.chooseChoir': 'ቡድን ይምረጡ',
    'auth.loadingChoirs': 'ቡድኖች በመጫን ላይ...',
    'auth.confirmPassword': 'የይለፍ ቃል ያረጋግጡ',
    'auth.registerAsMember': 'እንደ መዘምራን አባል ይመዝገቡ። መግቢያ ከማግኘትዎ በፊት የአስተዳዳሪ ማረጋገጫ ያስፈልጋል።',
    'auth.registerFailed': 'መመዝገብ አልተሳካም። እባክዎ ቅጹን ይመልሱ።',
    'auth.pleaseSelectChoir': 'እባክዎ ቡድን ይምረጡ።',
    'auth.pendingApproval': 'በማጽደቅ ላይ',
    'auth.registrationSubmitted': 'ምዝገባ ተልኳል',
    'auth.thankYou': 'እናመሰግናለን፣ {{name}}!',
    'auth.waitingApproval': 'መለያዎ በአሁኑ ጊዜ የአስተዳዳሪ ማጽደቅን በመጠባበቅ ላይ ነው።',
    'auth.reviewText': 'አስተዳዳሪው ምዝገባዎንና የቡድን ምደባዎን ይገመግማሉ። ከጸደቀ በኋላ በ{{email}} መግባት ይችላሉ።',
    'auth.yourEmail': 'ኢሜይልዎ',
    'auth.backToLogin': 'ወደ መግቢያ ተመለስ',
};

export { translationsEn, translationsAm };