import { createContext, useContext, useEffect, useState, useCallback, useMemo } from 'react';

const LanguageContext = createContext(null);

export const SUPPORTED_LANGUAGES = [
    { code: 'en', label: 'English', nativeName: 'English', flag: '🇬🇧' },
    { code: 'am', label: 'Amharic', nativeName: 'አማርኛ', flag: '🇪🇹' },
];

export const TRANSLATIONS = {
    en: {
        // Navigation & Sidebar
        'nav.dashboard': 'Dashboard',
        'nav.my_choir': 'My Choir',
        'nav.attendance': 'Attendance',
        'nav.songs': 'Songs',
        'nav.rehearsals': 'Rehearsals',
        'nav.performances': 'Performances',
        'nav.calendar': 'Calendar',
        'nav.my_attendance': 'My Attendance',
        'nav.my_performances': 'My Performances',
        'nav.choir_history': 'Choir History',
        'nav.my_profile': 'My Profile',
        'nav.settings': 'Settings',
        'nav.reports': 'Reports',
        'nav.activity_logs': 'Activity Logs',
        'nav.users': 'Users',
        'nav.roles_permissions': 'Roles & Permissions',
        'nav.members': 'Members',
        'nav.choirs': 'Choirs',
        'nav.sign_out': 'Sign Out',

        // Sidebar Section Headings
        'nav.section.my_choir': 'My Choir',
        'nav.section.music': 'Music',
        'nav.section.schedule': 'Schedule',
        'nav.section.ministry': 'Ministry',
        'nav.section.my_participation': 'My Participation',
        'nav.section.account': 'Account',
        'nav.section.organization': 'Organization',
        'nav.section.content': 'Content',
        'nav.section.user_management': 'User Management',
        'nav.section.reports': 'Reports',
        'nav.section.system': 'System',

        // Header & Choir Identity
        'header.all_choirs': 'All Choirs',
        'header.global_overview': 'Global Overview',
        'header.no_choir': 'No Choir',
        'header.not_assigned': 'Not assigned',
        'header.light_mode': 'Light Mode',
        'header.dark_mode': 'Dark Mode',
        'header.switch_to_light': 'Switch to light mode',
        'header.switch_to_dark': 'Switch to dark mode',
        'header.language': 'Language',
        'header.notifications': 'Notifications',
        'header.new_count': '{count} new',
        'header.mark_all_read': 'Mark all as read',
        'header.no_notifications': 'No notifications',
        'header.all_caught_up': "You're all caught up with choir updates.",
        'header.open_nav': 'Open navigation',
        'header.close_nav': 'Close navigation',
        'header.time.just_now': 'Just now',
        'header.time.m_ago': '{count}m ago',
        'header.time.h_ago': '{count}h ago',
        'header.time.d_ago': '{count}d ago',

        // Common Buttons & Actions
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.submit': 'Submit',
        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.view': 'View',
        'common.close': 'Close',
        'common.refresh': 'Refresh',
        'common.try_again': 'Try Again',
        'common.search': 'Search',
        'common.filter': 'Filter',
        'common.all': 'All',
        'common.back': 'Back',
        'common.view_details': 'View Details',
        'common.loading': 'Loading...',
        'common.status': 'Status',
        'common.actions': 'Actions',
        'common.play': 'Play',
        'common.download': 'Download',
        'common.download_audio': 'Download Audio',
        'common.lyrics': 'Lyrics',
        'common.date': 'Date',
        'common.time': 'Time',
        'common.location': 'Location',
        'common.venue': 'Venue',
        'common.tbd': 'TBD',
        'common.read_only': 'read-only',
        'common.required': 'Required',
        'common.optional': 'Optional',
        'common.clear': 'Clear',

        // Roles
        'role.member': 'Member',
        'role.team_leader': 'Team Leader',
        'role.admin': 'Admin',
        'role.super_admin': 'Super Admin',

        // Statuses
        'status.upcoming': 'Upcoming',
        'status.confirmed': 'Confirmed',
        'status.completed': 'Completed',
        'status.cancelled': 'Cancelled',
        'status.postponed': 'Postponed',
        'status.present': 'Present',
        'status.late': 'Late',
        'status.absent': 'Absent',
        'status.excused': 'Excused',
        'status.unmarked': 'Unmarked',
        'status.pending': 'Pending',
        'status.pending_review': 'Pending Review',
        'status.approved': 'Approved',
        'status.rejected': 'Rejected',
        'status.participated': 'Participated',
        'status.not_participated': 'Not Participated',

        // Dashboard
        'dashboard.portal': 'Member Portal',
        'dashboard.welcome_back': 'Welcome back, {name}',
        'dashboard.not_assigned_choir': 'You are not assigned to a choir yet.',
        'dashboard.no_choir_message': 'Once an administrator assigns you to a choir, your schedule, performances and attendance will appear here.',
        'dashboard.load_error': 'Could not load dashboard',
        'dashboard.upcoming_performances': 'Upcoming Performances',
        'dashboard.upcoming_rehearsals': 'Upcoming Rehearsals',
        'dashboard.attendance': 'Attendance',
        'dashboard.my_performances': 'My Performances',
        'dashboard.scheduled_ahead': 'Scheduled ahead',
        'dashboard.scheduled_count': 'You are scheduled',
        'dashboard.no_records_yet': 'No records yet',
        'dashboard.attendance_hint': '{absent} absent · {late} late',
        'dashboard.upcoming_performance': 'Upcoming Performance',
        'dashboard.next_rehearsal': 'Next Rehearsal',
        'dashboard.view_performance': 'View Performance',
        'dashboard.no_upcoming_performances': 'No upcoming performances.',
        'dashboard.no_upcoming_rehearsals': 'No upcoming rehearsals.',
        'dashboard.no_performance_participation': 'No performance participation yet.',

        // Songs Page
        'songs.library_title': 'Music Library',
        'songs.library_subtitle': '{choir} songs and submissions',
        'songs.default_subtitle': 'Your choir song library',
        'songs.submit_song': 'Submit Song',
        'songs.submit_a_song': 'Submit a Song',
        'songs.tab_choir_library': 'Choir Library ({count})',
        'songs.tab_my_submissions': 'My Submissions',
        'songs.approved_songs': 'Approved Songs',
        'songs.with_lyrics': 'With Lyrics',
        'songs.with_audio': 'With Audio',
        'songs.search_placeholder_library': 'Search songs by title, artist, or composer…',
        'songs.search_placeholder_submissions': 'Search my submissions by title, artist, or composer…',
        'songs.col_song': 'Song',
        'songs.col_key': 'Key',
        'songs.col_status': 'Status',
        'songs.col_available': 'Available',
        'songs.col_actions': 'Actions',
        'songs.badge_lyrics': 'Lyrics',
        'songs.badge_audio': 'Audio',
        'songs.key_label': 'Key: {key}',
        'songs.artist_label': 'Artist: {artist}',
        'songs.admin_feedback': 'Admin Feedback:',
        'songs.submission_status': 'Submission Status',
        'songs.no_songs_found': 'No songs found in this choir library',
        'songs.no_songs_found_desc': 'Approved choir songs will appear here once reviewed by the administrator.',
        'songs.no_submissions': 'No song submissions yet',
        'songs.no_submissions_desc': "You haven't submitted any songs yet. Click below to submit a song for review.",
        'songs.modal_submit_title': 'Submit Song for Review',
        'songs.process_title': 'Submission & Approval Process',
        'songs.process_desc': 'Submitted songs are saved with status Pending. Administrators review submissions to approve, reject, or request edits. Once approved, the song appears in the worship music library.',
        'songs.field_choir': 'Choir',
        'songs.field_select_choir': 'Select Choir...',
        'songs.submitting_for_choir': 'Submitting for Choir:',
        'songs.field_title': 'Song Title',
        'songs.title_placeholder': 'e.g. Halleluya LeAmlak',
        'songs.field_composer': 'Composer',
        'songs.composer_placeholder': 'Songwriter / Composer name',
        'songs.field_artist': 'Artist / Lead Singer',
        'songs.artist_placeholder': 'Lead vocalist or original performer',
        'songs.field_key': 'Original Key',
        'songs.field_scale': 'Musical Scale',
        'songs.scale_major': 'Major',
        'songs.scale_minor': 'Minor',
        'songs.scale_ethiopian': 'Ethiopian / Traditional',
        'songs.field_scale_mode': 'Scale Mode / Melody Type',
        'songs.scale_mode_placeholder': 'e.g. Tizita, Bati, Ambassel, Anchihoye',
        'songs.field_description': 'Description / Notes',
        'songs.description_placeholder': 'Background story, occasion, spiritual theme...',
        'songs.field_lyrics': 'Song Lyrics',
        'songs.lyrics_placeholder': "Enter full lyrics here...",
        'songs.field_audio': 'Audio Recording (MP3, WAV, M4A)',
        'songs.field_cover': 'Cover Image / Sheet Music (PNG, JPG, PDF)',
        'songs.btn_submit_review': 'Submit for Review',
        'songs.submit_success': 'Your song was submitted successfully and is now pending administrator review.',
        'songs.load_error': 'Unable to load songs.',
        'songs.likes': '{count} likes',

        // Lyrics Modal
        'lyrics.modal_title': 'Song Lyrics',
        'lyrics.section_heading': 'Lyrics',
        'lyrics.download_audio': 'Download Audio',

        // Performances Page
        'performances.title': 'Performances',
        'performances.subtitle': 'View upcoming performances, prepare your songs, and stay connected with your choir schedule.',
        'performances.filter_upcoming': 'Upcoming',
        'performances.filter_past': 'Past',
        'performances.filter_all': 'All',
        'performances.card_upcoming': 'Upcoming',
        'performances.card_this_month': 'This Month',
        'performances.card_completed': 'Completed',
        'performances.card_scheduled_ahead': 'Scheduled ahead',
        'performances.card_in_month': 'Performances in this month',
        'performances.card_past': 'Past performances',
        'performances.count_single': '{count} performance',
        'performances.count_plural': '{count} performances',
        'performances.empty_upcoming': 'No upcoming performances',
        'performances.empty_upcoming_desc': "Your choir's upcoming performances will appear here.",
        'performances.empty_past': 'No past performances',
        'performances.empty_past_desc': "Your choir's past performances will appear here.",
        'performances.empty_none': 'No performances found',
        'performances.empty_none_desc': 'No performances are scheduled for your choir yet.',
        'performances.modal_title': 'Performance Details',
        'performances.modal_songs': 'Songs to Prepare',
        'performances.modal_no_songs': 'No specific songs listed yet.',
        'performances.modal_participation': 'Your Participation Status',
        'performances.load_error': 'Unable to load performances. Please try again.',
        'performances.song_count': '{count} song',
        'performances.songs_count': '{count} songs',

        // Attendance Page
        'attendance.title': 'My Attendance',
        'attendance.total_events': 'Total Events',
        'attendance.scheduled_sessions': 'Scheduled Sessions',
        'attendance.present': 'Present',
        'attendance.on_time': 'On Time',
        'attendance.late': 'Late',
        'attendance.after_start': 'After Start',
        'attendance.absent': 'Absent',
        'attendance.missed': 'Missed',
        'attendance.rate': 'Attendance Rate',
        'attendance.search_placeholder': 'Search past events or dates...',
        'attendance.filter_all': 'All',
        'attendance.filter_present': 'Present',
        'attendance.filter_late': 'Late',
        'attendance.filter_absent': 'Absent',
        'attendance.filter_excused': 'Excused',
        'attendance.col_date': 'Date',
        'attendance.col_event': 'Event / Performance',
        'attendance.col_choir': 'Choir',
        'attendance.col_status': 'Status',
        'attendance.col_check_in': 'Check-In',
        'attendance.col_check_out': 'Check-Out',
        'attendance.empty_title': 'No attendance records found',
        'attendance.empty_search': 'Try clearing your search or filter.',
        'attendance.empty_none': 'No recorded attendance sessions yet.',
        'attendance.loading_records': 'Loading your attendance records...',

        // My Choir Page
        'choir.title': 'My Choir',
        'choir.members': 'Members',
        'choir.leader': 'Leader',
        'choir.not_listed': 'Not listed',
        'choir.no_description': 'No description provided.',
        'choir.members_list': 'Choir Members',
        'choir.no_members': 'No members to display.',
        'choir.not_assigned_title': 'No choir assigned',
        'choir.not_assigned_desc': 'You are not assigned to a choir yet. An administrator will assign you soon.',
        'choir.load_error': 'Could not load choir',

        // Profile Page
        'profile.title': 'My Profile',
        'profile.full_name': 'Full name',
        'profile.email': 'Email',
        'profile.phone': 'Phone',
        'profile.phone_optional': 'Optional',
        'profile.change_password': 'Change password (optional)',
        'profile.new_password': 'New password',
        'profile.confirm_password': 'Confirm new password',
        'profile.leave_blank': 'Leave blank to keep current',
        'profile.save_changes': 'Save changes',
        'profile.update_success': 'Profile updated successfully.',
        'profile.load_error': 'Unable to load your profile.',

        // Notifications Page
        'notifications.title': 'Notifications',
        'notifications.empty_title': 'No notifications yet',
        'notifications.empty_desc': "You'll see choir announcements and updates here.",
        'notifications.load_error': 'Unable to load notifications.',

        // Settings Page
        'settings.title': 'Account & Preferences',
        'settings.subtitle': 'Manage your personal profile, credentials, security, and notification preferences.',
        'settings.tab_profile': 'Personal Info',
        'settings.tab_contact': 'Contact Details',
        'settings.tab_security': 'Security',
        'settings.tab_preferences': 'Preferences',
        'settings.tab_deactivate': 'Deactivate',
        'settings.personal_info': 'Personal Information',
        'settings.personal_info_desc': 'Update your personal details, profile avatar, and choir bio.',
        'settings.photo_label': 'Profile Photo / Avatar',
        'settings.upload_photo': 'Upload New Photo',
        'settings.remove_photo': 'Remove Photo',
        'settings.undo_remove': 'Undo remove',
        'settings.photo_hint': 'JPG, PNG, GIF or WebP up to 2MB.',
        'settings.username': 'Username',
        'settings.username_hint': 'Letters, numbers, dashes, and underscores.',
        'settings.role_title': 'Job Title / Choir Role',
        'settings.role_title_placeholder': 'e.g. Lead Vocalist, Tenor Section Leader, Sound Engineer',
        'settings.bio': 'Bio & About Me',
        'settings.bio_placeholder': 'Share a brief introduction about your choir journey and background...',
        'settings.save_personal': 'Save Personal Info',
        'settings.contact_details': 'Contact Details',
        'settings.contact_desc': 'Manage your verified email address and primary telephone number.',
        'settings.primary_email': 'Primary Email Address',
        'settings.verified': 'Verified',
        'settings.unverified': 'Unverified',
        'settings.verify_email': 'Verify Email',
        'settings.unverified_alert': 'Your email is not verified yet. Verify it now to secure your account.',
        'settings.phone_label': 'Phone Number (Ethiopian format: 09XXXXXXXX or 07XXXXXXXX)',
        'settings.phone_hint': 'Must be exactly 10 Ethiopian digits (e.g. 0911223344 or 0711223344).',
        'settings.save_contact': 'Save Contact Details',
        'settings.security_title': 'Security & Authentication',
        'settings.pwd_reset_title': 'Password Reset Link',
        'settings.pwd_reset_desc': 'Trigger a password reset link to your registered email address.',
        'settings.send_reset_link': 'Send Reset Link',
        'settings.change_password': 'Change Password',
        'settings.current_password': 'Current Password',
        'settings.update_password': 'Update Password',
        'settings.region_language': 'Region & Language',
        'settings.region_desc': 'Customize your preferred display language and timezone region.',
        'settings.preferred_language': 'Preferred Language',
        'settings.timezone': 'Timezone',
        'settings.save_preferences': 'Save Preferences',
        'settings.notification_prefs': 'Notification Preferences',
        'settings.notification_desc': 'Choose which alerts and updates you wish to receive.',
        'settings.deactivate_title': 'Deactivate Account',
        'settings.deactivate_warning': 'Once you deactivate your account, you will lose access to choir materials, schedules, and recordings. This action cannot be easily undone.',
        'settings.btn_deactivate': 'Deactivate My Account',
        'settings.load_error': 'Could not load account settings.',
        'settings.save_success': 'Settings saved successfully.',
    },
    am: {
        // Navigation & Sidebar
        'nav.dashboard': 'ዳሽቦርድ',
        'nav.my_choir': 'የእኔ መዘምራን',
        'nav.attendance': 'ክትትል',
        'nav.songs': 'መዝሙራት',
        'nav.rehearsals': 'ልምምዶች',
        'nav.performances': 'ዝግጅቶች',
        'nav.calendar': 'ቀን መቁጠሪያ',
        'nav.my_attendance': 'የእኔ ክትትል',
        'nav.my_performances': 'የእኔ ዝግጅቶች',
        'nav.choir_history': 'የመዘምራን ታሪክ',
        'nav.my_profile': 'የእኔ መገለጫ',
        'nav.settings': 'ቅንብሮች',
        'nav.reports': 'ሪፖርቶች',
        'nav.activity_logs': 'የእንቅስቃሴ መዝገብ',
        'nav.users': 'ተጠቃሚዎች',
        'nav.roles_permissions': 'ሚናዎች እና ፈቃዶች',
        'nav.members': 'አባላት',
        'nav.choirs': 'መዘምራን',
        'nav.sign_out': 'ውጣ',

        // Sidebar Section Headings
        'nav.section.my_choir': 'የእኔ መዘምራን',
        'nav.section.music': 'መዝሙር',
        'nav.section.schedule': 'መርሐግብር',
        'nav.section.ministry': 'አገልግሎት',
        'nav.section.my_participation': 'የእኔ ተሳትፎ',
        'nav.section.account': 'መለያ',
        'nav.section.organization': 'ድርጅት',
        'nav.section.content': 'ይዘት',
        'nav.section.user_management': 'የተጠቃሚዎች አስተዳደር',
        'nav.section.reports': 'ሪፖርቶች',
        'nav.section.system': 'ስርዓት',

        // Header & Choir Identity
        'header.all_choirs': 'ሁሉም መዘምራን',
        'header.global_overview': 'አጠቃላይ እይታ',
        'header.no_choir': 'መዘምራን አልተመደበም',
        'header.not_assigned': 'አልተመደበም',
        'header.light_mode': 'ነጭ ገጽታ',
        'header.dark_mode': 'ጨለማ ገጽታ',
        'header.switch_to_light': 'ወደ ነጭ ገጽታ ቀይር',
        'header.switch_to_dark': 'ወደ ጨለማ ገጽታ ቀይር',
        'header.language': 'ቋንቋ',
        'header.notifications': 'ማሳወቂያዎች',
        'header.new_count': '{count} አዲስ',
        'header.mark_all_read': 'ሁሉንም እንደተነበቡ ምልክት አድርግ',
        'header.no_notifications': 'ምንም ማሳወቂያ የለም',
        'header.all_caught_up': 'የመዘምራን ማሳወቂያዎችን በሙሉ ተመልክተዋል።',
        'header.open_nav': 'ማውጫውን ክፈት',
        'header.close_nav': 'ማውጫውን ዝጋ',
        'header.time.just_now': 'አሁን',
        'header.time.m_ago': 'ከ{count} ደቂቃ በፊት',
        'header.time.h_ago': 'ከ{count} ሰዓት በፊት',
        'header.time.d_ago': 'ከ{count} ቀን በፊት',

        // Common Buttons & Actions
        'common.save': 'አስቀምጥ',
        'common.cancel': 'ሰርዝ',
        'common.submit': 'አስገባ',
        'common.delete': 'አጥፋ',
        'common.edit': 'አርትዕ',
        'common.view': 'ተመልከት',
        'common.close': 'ዝጋ',
        'common.refresh': 'አድስ',
        'common.try_again': 'እንደገና ሞክር',
        'common.search': 'ፈልግ',
        'common.filter': 'አጣራ',
        'common.all': 'ሁሉም',
        'common.back': 'ተመለስ',
        'common.view_details': 'ዝርዝሩን ተመልከት',
        'common.loading': 'በመጫን ላይ...',
        'common.status': 'ሁኔታ',
        'common.actions': 'እርምጃዎች',
        'common.play': 'አጫውት',
        'common.download': 'አውርድ',
        'common.download_audio': 'ድምጹን አውርድ',
        'common.lyrics': 'ግጥም',
        'common.date': 'ቀን',
        'common.time': 'ሰዓት',
        'common.location': 'አካባቢ',
        'common.venue': 'ቦታ',
        'common.tbd': 'ይገለጻል',
        'common.read_only': 'ማየት ብቻ',
        'common.required': 'አስፈላጊ',
        'common.optional': 'አማራጭ',
        'common.clear': 'አጽዳ',

        // Roles
        'role.member': 'አባል',
        'role.team_leader': 'የቡድን መሪ',
        'role.admin': 'አስተዳዳሪ',
        'role.super_admin': 'ዋና አስተዳዳሪ',

        // Statuses
        'status.upcoming': 'መጪ',
        'status.confirmed': 'የተረጋገጠ',
        'status.completed': 'የተጠናቀቀ',
        'status.cancelled': 'የተሰረዘ',
        'status.postponed': 'የተላለፈ',
        'status.present': 'የተገኘ',
        'status.late': 'የዘገየ',
        'status.absent': 'የቀረ',
        'status.excused': 'ፈቃድ የተሰጠው',
        'status.unmarked': 'ያልተመዘገበ',
        'status.pending': 'በመጠባበቅ ላይ',
        'status.pending_review': 'በግምገማ ላይ',
        'status.approved': 'የጸደቀ',
        'status.rejected': 'ውድቅ የተደረገ',
        'status.participated': 'ተሳትፈዋል',
        'status.not_participated': 'አልተሳተፉም',

        // Dashboard
        'dashboard.portal': 'የአባላት መግቢያ',
        'dashboard.welcome_back': 'እንኳን ደህና መጡ፣ {name}',
        'dashboard.not_assigned_choir': 'እስካሁን ምንም መዘምራን አልተመደቡም።',
        'dashboard.no_choir_message': 'አስተዳዳሪው መዘምራን ሲመድብልዎ መርሐግብርዎ፣ ዝግጅቶችዎ እና ክትትልዎ እዚህ ይታያሉ።',
        'dashboard.load_error': 'ዳሽቦርዱን መጫን አልተቻለም',
        'dashboard.upcoming_performances': 'መጪ ዝግጅቶች',
        'dashboard.upcoming_rehearsals': 'መጪ ልምምዶች',
        'dashboard.attendance': 'ክትትል',
        'dashboard.my_performances': 'የእኔ ዝግጅቶች',
        'dashboard.scheduled_ahead': 'የተያዙ',
        'dashboard.scheduled_count': 'ተመድበዋል',
        'dashboard.no_records_yet': 'ምንም መረጃ የለም',
        'dashboard.attendance_hint': '{absent} የቀሩ · {late} የዘገዩ',
        'dashboard.upcoming_performance': 'መጪ ዝግጅት',
        'dashboard.next_rehearsal': 'ቀጣይ ልምምድ',
        'dashboard.view_performance': 'ዝግጅቱን ይመልከቱ',
        'dashboard.no_upcoming_performances': 'ምንም መጪ ዝግጅቶች የሉም።',
        'dashboard.no_upcoming_rehearsals': 'ምንም መጪ ልምምዶች የሉም።',
        'dashboard.no_performance_participation': 'እስካሁን ምንም የተሳትፎ መረጃ የለም።',

        // Songs Page
        'songs.library_title': 'የመዝሙር ማህደር',
        'songs.library_subtitle': 'የ{choir} መዝሙራት እና የቀረቡ',
        'songs.default_subtitle': 'የመዘምራን የመዝሙር ማህደር',
        'songs.submit_song': 'መዝሙር አስገባ',
        'songs.submit_a_song': 'መዝሙር አስገባ',
        'songs.tab_choir_library': 'የመዘምራን ማህደር ({count})',
        'songs.tab_my_submissions': 'የእኔ ማመልከቻዎች',
        'songs.approved_songs': 'የጸደቁ መዝሙራት',
        'songs.with_lyrics': 'ግጥም ያላቸው',
        'songs.with_audio': 'ድምጽ ያላቸው',
        'songs.search_placeholder_library': 'መዝሙራትን በስም፣ አርቲስት ወይም ዜማ ደራሲ ይፈልጉ…',
        'songs.search_placeholder_submissions': 'ያስገቧቸውን መዝሙራት በስም ወይም አርቲስት ይፈልጉ…',
        'songs.col_song': 'መዝሙር',
        'songs.col_key': 'ኪይ',
        'songs.col_status': 'ሁኔታ',
        'songs.col_available': 'የሚገኙ',
        'songs.col_actions': 'እርምጃዎች',
        'songs.badge_lyrics': 'ግጥም',
        'songs.badge_audio': 'ድምጽ',
        'songs.key_label': 'ኪይ: {key}',
        'songs.artist_label': 'አርቲስት: {artist}',
        'songs.admin_feedback': 'የአስተዳዳሪ አስተያየት:',
        'songs.submission_status': 'የማመልከቻ ሁኔታ',
        'songs.no_songs_found': 'በዚህ የመዘምራን ማህደር ምንም መዝሙር አልተገኘም',
        'songs.no_songs_found_desc': 'የጸደቁ የመዘምራን መዝሙራት በአስተዳዳሪው ሲገመገሙ እዚህ ይታያሉ።',
        'songs.no_submissions': 'እስካሁን ምንም የቀረበ መዝሙር የለም',
        'songs.no_submissions_desc': 'እስካሁን ምንም መዝሙር አላስገቡም። መዝሙር ለግምገማ ለማቅረብ ከታች ያለውን ይጫኑ።',
        'songs.modal_submit_title': 'መዝሙር ለግምገማ አስገባ',
        'songs.process_title': 'የማቅረብ እና የማጽደቅ ሂደት',
        'songs.process_desc': 'የቀረቡ መዝሙራት በመጠባበቅ ላይ ይቀመጣሉ። አስተዳዳሪዎች መዝሙሩን መርምረው ያጸድቃሉ ወይም ማስተካከያ ይጠይቃሉ። ሲጸድቅ በይፋዊ ማህደር ውስጥ ይካተታል።',
        'songs.field_choir': 'መዘምራን',
        'songs.field_select_choir': 'መዘምራን ይምረጡ...',
        'songs.submitting_for_choir': 'የሚቀርበው ለመዘምራን:',
        'songs.field_title': 'የመዝሙር ስም',
        'songs.title_placeholder': 'ለምሳሌ፦ ሃሌ ሉያ ለአምላክ',
        'songs.field_composer': 'ዜማ ደራሲ',
        'songs.composer_placeholder': 'የግጥም ወይም ዜማ ደራሲ ስም',
        'songs.field_artist': 'አርቲስት / መሪ ዘማሪ',
        'songs.artist_placeholder': 'ዋና ዘማሪ ወይም የመጀመሪያው አቅራቢ',
        'songs.field_key': 'ዋና ኪይ',
        'songs.field_scale': 'የሙዚቃ ስኬል',
        'songs.scale_major': 'ሜጀር',
        'songs.scale_minor': 'ማይነር',
        'songs.scale_ethiopian': 'የኢትዮጵያ / ባህላዊ',
        'songs.field_scale_mode': 'የስኬል ዓይነት (ቅኝት)',
        'songs.scale_mode_placeholder': 'ለምሳሌ፦ ትዝታ፣ ባቲ፣ አምባሰል፣ አንቺሆዬ',
        'songs.field_description': 'መግለጫ / ማስታወሻ',
        'songs.description_placeholder': 'የመዝሙሩ አመጣጥ፣ ወቅት፣ መንፈሳዊ ጭብጥ...',
        'songs.field_lyrics': 'የመዝሙር ግጥም',
        'songs.lyrics_placeholder': 'ሙሉውን የመዝሙር ግጥም እዚህ ያስገቡ...',
        'songs.field_audio': 'የድምጽ ቅጂ (MP3, WAV, M4A)',
        'songs.field_cover': 'የሽፋን ምስል / ኖታ (PNG, JPG, PDF)',
        'songs.btn_submit_review': 'ለግምገማ አስገባ',
        'songs.submit_success': 'መዝሙርዎ በተሳካ ሁኔታ ቀርቧል፤ በአስተዳዳሪው ግምገማ ላይ ይገኛል።',
        'songs.load_error': 'መዝሙራትን መጫን አልተቻለም።',
        'songs.likes': '{count} ወደዋል',

        // Lyrics Modal
        'lyrics.modal_title': 'የመዝሙር ግጥም',
        'lyrics.section_heading': 'ግጥም',
        'lyrics.download_audio': 'ድምጹን አውርድ',

        // Performances Page
        'performances.title': 'ዝግጅቶች',
        'performances.subtitle': 'መጪ ዝግጅቶችን ይመልከቱ፣ መዝሙራትን ያዘጋጁ፣ እንዲሁም ከመዘምራን መርሐግብር ጋር ይገናኙ።',
        'performances.filter_upcoming': 'መጪ',
        'performances.filter_past': 'ያለፉ',
        'performances.filter_all': 'ሁሉም',
        'performances.card_upcoming': 'መጪ',
        'performances.card_this_month': 'በዚህ ወር',
        'performances.card_completed': 'የተጠናቀቁ',
        'performances.card_scheduled_ahead': 'የተያዙ',
        'performances.card_in_month': 'በዚህ ወር ያሉ ዝግጅቶች',
        'performances.card_past': 'ያለፉ ዝግጅቶች',
        'performances.count_single': '{count} ዝግጅት',
        'performances.count_plural': '{count} ዝግጅቶች',
        'performances.empty_upcoming': 'ምንም መጪ ዝግጅቶች የሉም',
        'performances.empty_upcoming_desc': 'የመዘምራን መጪ ዝግጅቶች ሲኖሩ እዚህ ይታያሉ።',
        'performances.empty_past': 'ምንም ያለፉ ዝግጅቶች የሉም',
        'performances.empty_past_desc': 'የመዘምራን ያለፉ ዝግጅቶች እዚህ ይታያሉ።',
        'performances.empty_none': 'ምንም ዝግጅት አልተገኘም',
        'performances.empty_none_desc': 'እስካሁን ለመዘምራን የተያዘ ምንም ዝግጅት የለም።',
        'performances.modal_title': 'የዝግጅት ዝርዝር',
        'performances.modal_songs': 'የሚዘጋጁ መዝሙራት',
        'performances.modal_no_songs': 'ምንም የተዘረዘረ መዝሙር የለም።',
        'performances.modal_participation': 'የእርስዎ የተሳትፎ ሁኔታ',
        'performances.load_error': 'ዝግጅቶችን መጫን አልተቻለም። እባክዎ እንደገና ይሞክሩ።',
        'performances.song_count': '{count} መዝሙር',
        'performances.songs_count': '{count} መዝሙራት',

        // Attendance Page
        'attendance.title': 'የእኔ ክትትል',
        'attendance.total_events': 'አጠቃላይ ዝግጅቶች',
        'attendance.scheduled_sessions': 'የተመደቡ መርሐግብሮች',
        'attendance.present': 'የተገኙ',
        'attendance.on_time': 'በሰዓቱ',
        'attendance.late': 'የዘገዩ',
        'attendance.after_start': 'ከጀመረ በኋላ',
        'attendance.absent': 'የቀሩ',
        'attendance.missed': 'ያመለጠ',
        'attendance.rate': 'የክትትል ምጣኔ',
        'attendance.search_placeholder': 'ያለፉ ዝግጅቶችን ወይም ቀኖችን ይፈልጉ...',
        'attendance.filter_all': 'ሁሉም',
        'attendance.filter_present': 'የተገኙ',
        'attendance.filter_late': 'የዘገዩ',
        'attendance.filter_absent': 'የቀሩ',
        'attendance.filter_excused': 'ፈቃድ',
        'attendance.col_date': 'ቀን',
        'attendance.col_event': 'ዝግጅት / መርሐግብር',
        'attendance.col_choir': 'መዘምራን',
        'attendance.col_status': 'ሁኔታ',
        'attendance.col_check_in': 'የመግቢያ ሰዓት',
        'attendance.col_check_out': 'የመውጫ ሰዓት',
        'attendance.empty_title': 'ምንም የክትትል መረጃ አልተገኘም',
        'attendance.empty_search': 'ፍለጋዎን ወይም ማጣሪያዎን ያጽዱ።',
        'attendance.empty_none': 'እስካሁን የተመዘገበ ምንም የክትትል መረጃ የለም።',
        'attendance.loading_records': 'የክትትል መዝገብዎን በመጫን ላይ...',

        // My Choir Page
        'choir.title': 'የእኔ መዘምራን',
        'choir.members': 'አባላት',
        'choir.leader': 'መሪ',
        'choir.not_listed': 'አልተዘረዘረም',
        'choir.no_description': 'ምንም መግለጫ አልተሰጠም።',
        'choir.members_list': 'የመዘምራን አባላት',
        'choir.no_members': 'የሚታዩ አባላት የሉም።',
        'choir.not_assigned_title': 'መዘምራን አልተመደበም',
        'choir.not_assigned_desc': 'እስካሁን ወደ መዘምራን አልተመደቡም። አስተዳዳሪው በቅርቡ ይመድብዎታል።',
        'choir.load_error': 'መዘምራንን መጫን አልተቻለም',

        // Profile Page
        'profile.title': 'የእኔ መገለጫ',
        'profile.full_name': 'ሙሉ ስም',
        'profile.email': 'ኢሜይል',
        'profile.phone': 'ስልክ ቁጥር',
        'profile.phone_optional': 'አማራጭ',
        'profile.change_password': 'የይለፍ ቃል ቀይር (አማራጭ)',
        'profile.new_password': 'አዲስ የይለፍ ቃል',
        'profile.confirm_password': 'አዲሱን የይለፍ ቃል አረጋግጥ',
        'profile.leave_blank': 'ያለውን የይለፍ ቃል ለመጠበቅ ባዶ ይተዉት',
        'profile.save_changes': 'ለውጦችን አስቀምጥ',
        'profile.update_success': 'መገለጫዎ በተሳካ ሁኔታ ተሻሽሏል።',
        'profile.load_error': 'መገለጫዎን መጫን አልተቻለም።',

        // Notifications Page
        'notifications.title': 'ማሳወቂያዎች',
        'notifications.empty_title': 'ምንም ማሳወቂያ የለም',
        'notifications.empty_desc': 'የመዘምራን ማስታወቂያዎችን እና ዝመናዎችን እዚህ ያገኛሉ።',
        'notifications.load_error': 'ማሳወቂያዎችን መጫን አልተቻለም።',

        // Settings Page
        'settings.title': 'መለያ እና ምርጫዎች',
        'settings.subtitle': 'የግል መገለጫዎን፣ ምስክርነቶችን፣ ደህንነትን እና የማሳወቂያ ምርጫዎችን ያስተዳድሩ።',
        'settings.tab_profile': 'የግል መረጃ',
        'settings.tab_contact': 'የመገናኛ አድራሻ',
        'settings.tab_security': 'ደህንነት',
        'settings.tab_preferences': 'ምርጫዎች',
        'settings.tab_deactivate': 'መለያ አቦዝን',
        'settings.personal_info': 'የግል መረጃ',
        'settings.personal_info_desc': 'የግል መረጃዎን፣ የመገለጫ ፎቶዎን እና የመዘምራን ታሪክዎን ያሻሽሉ።',
        'settings.photo_label': 'የመገለጫ ፎቶ',
        'settings.upload_photo': 'አዲስ ፎቶ ጫን',
        'settings.remove_photo': 'ፎቶ አስወግድ',
        'settings.undo_remove': 'መልስ',
        'settings.photo_hint': 'JPG, PNG, GIF ወይም WebP እስከ 2MB ድረስ።',
        'settings.username': 'የተጠቃሚ ስም',
        'settings.username_hint': 'ፊደላት፣ ቁጥሮች፣ ሰረዞች እና የግርጌ ሰረዞች ብቻ።',
        'settings.role_title': 'የስራ ድርሻ / የመዘምራን ሚና',
        'settings.role_title_placeholder': 'ለምሳሌ፦ መሪ ዘማሪ፣ የቴነር ክፍል መሪ፣ የድምጽ ባለሙያ',
        'settings.bio': 'ስለ እኔ አጭር መግለጫ',
        'settings.bio_placeholder': 'ስለ መዘምራን አገልግሎትዎ እና ጉዞዎ አጭር መግለጫ ያጋሩ...',
        'settings.save_personal': 'የግል መረጃ አስቀምጥ',
        'settings.contact_details': 'የመገናኛ አድራሻ',
        'settings.contact_desc': 'የተረጋገጠውን ኢሜይልዎን እና ዋና የስልክ ቁጥርዎን ያስተዳድሩ።',
        'settings.primary_email': 'ዋና የኢሜይል አድራሻ',
        'settings.verified': 'የተረጋገጠ',
        'settings.unverified': 'ያልተረጋገጠ',
        'settings.verify_email': 'ኢሜይል አረጋግጥ',
        'settings.unverified_alert': 'ኢሜይልዎ እስካሁን አልተረጋገጠም። መለያዎን ደህንነቱ የተጠበቀ ለማድረግ አሁን ያረጋግጡ።',
        'settings.phone_label': 'ስልክ ቁጥር (የኢትዮጵያ ቅርጸት፦ 09XXXXXXXX ወይም 07XXXXXXXX)',
        'settings.phone_hint': 'በትክክል 10 የኢትዮጵያ አሃዞች መሆን አለበት (ለምሳሌ፦ 0911223344 ወይም 0711223344)።',
        'settings.save_contact': 'የመገናኛ አድራሻ አስቀምጥ',
        'settings.security_title': 'ደህንነት እና ማረጋገጫ',
        'settings.pwd_reset_title': 'የይለፍ ቃል ዳግም ማስጀመሪያ አገናኝ',
        'settings.pwd_reset_desc': 'ወደ ተመዘገበው ኢሜይልዎ የይለፍ ቃል ዳግም ማስጀመሪያ አገናኝ ይላኩ።',
        'settings.send_reset_link': 'ዳግም ማስጀመሪያ አገናኝ ላክ',
        'settings.change_password': 'የይለፍ ቃል ቀይር',
        'settings.current_password': 'የአሁኑ የይለፍ ቃል',
        'settings.update_password': 'የይለፍ ቃል አሻሽል',
        'settings.region_language': 'አካባቢ እና ቋንቋ',
        'settings.region_desc': 'የሚመርጡትን የማሳያ ቋንቋ እና የሰዓት ሰቅ ያስተካክሉ።',
        'settings.preferred_language': 'ተመራጭ ቋንቋ',
        'settings.timezone': 'የሰዓት ሰቅ (Timezone)',
        'settings.save_preferences': 'ምርጫዎችን አስቀምጥ',
        'settings.notification_prefs': 'የማሳወቂያ ምርጫዎች',
        'settings.notification_desc': 'ሊቀበሏቸው የሚፈልጓቸውን ማሳወቂያዎች እና ዝመናዎች ይምረጡ።',
        'settings.deactivate_title': 'መለያ አቦዝን',
        'settings.deactivate_warning': 'መለያዎን ካቦዘኑ በኋላ የመዘምራን መርሐግብሮችን፣ ቁሳቁሶችን እና ቅጂዎችን ማግኘት አይችሉም። ይህ እርምጃ በቀላሉ አይቀለበስም።',
        'settings.btn_deactivate': 'መለያዬን አቦዝን',
        'settings.load_error': 'የመለያ ቅንብሮችን መጫን አልተቻለም።',
        'settings.save_success': 'ቅንብሮች በተሳካ ሁኔታ ተቀምጠዋል።',
    },
};

export function LanguageProvider({ children }) {
    const [language, setLanguageState] = useState(() => {
        if (typeof window === 'undefined') return 'en';
        const saved = window.localStorage.getItem('member_language');
        return saved === 'am' || saved === 'en' ? saved : 'en';
    });

    const setLanguage = useCallback((newLang) => {
        if (newLang !== 'en' && newLang !== 'am') return;
        setLanguageState(newLang);
        if (typeof window !== 'undefined') {
            window.localStorage.setItem('member_language', newLang);
            document.documentElement.lang = newLang;
        }
    }, []);

    useEffect(() => {
        if (typeof window !== 'undefined') {
            document.documentElement.lang = language;
        }
    }, [language]);

    const t = useCallback((key, paramsOrFallback, maybeParams) => {
        let fallback = typeof paramsOrFallback === 'string' ? paramsOrFallback : key;
        let params = typeof paramsOrFallback === 'object' ? paramsOrFallback : maybeParams;

        const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
        let text = langDict[key] ?? TRANSLATIONS.en[key] ?? fallback;

        if (params && typeof params === 'object') {
            Object.entries(params).forEach(([paramKey, val]) => {
                text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(val ?? ''));
            });
        }
        return text;
    }, [language]);

    const currentLanguageObj = useMemo(() => {
        return SUPPORTED_LANGUAGES.find((l) => l.code === language) || SUPPORTED_LANGUAGES[0];
    }, [language]);

    return (
        <LanguageContext.Provider
            value={{
                language,
                setLanguage,
                t,
                currentLanguage: currentLanguageObj,
                supportedLanguages: SUPPORTED_LANGUAGES,
                isAmharic: language === 'am',
            }}
        >
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const ctx = useContext(LanguageContext);
    if (!ctx) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return ctx;
}

export default LanguageContext;
